# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ItemStationsEsu")

model.instance <- ItemStationsEsu$new()

test_that("CODE", {
  # tests for the property `CODE` (character)
  # Code de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE`, "EXPECTED_RESULT")
})

test_that("LONGITUDE", {
  # tests for the property `LONGITUDE` (numeric)
  # Longitude de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`LONGITUDE`, "EXPECTED_RESULT")
})

test_that("LATITUDE", {
  # tests for the property `LATITUDE` (numeric)
  # Latitude de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`LATITUDE`, "EXPECTED_RESULT")
})

