# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DatafileSimpleExtendedFilters")

model.instance <- DatafileSimpleExtendedFilters$new()

test_that("name", {
  # tests for the property `name` (character)
  # Nom du filtre étendu

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("columns", {
  # tests for the property `columns` (array[character])
  # La liste des colonnes sur lesquelles s&#39;appliquent le filtre étendu

  # uncomment below to test the property 
  #expect_equal(model.instance$`columns`, "EXPECTED_RESULT")
})

test_that("filters", {
  # tests for the property `filters` (array[character])
  # Liste des type de filtres disponibles pour ce filtre étendu.

  # uncomment below to test the property 
  #expect_equal(model.instance$`filters`, "EXPECTED_RESULT")
})

