# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ItemPorts")

model.instance <- ItemPorts$new()

test_that("CODE", {
  # tests for the property `CODE` (character)
  # Code du port

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE`, "EXPECTED_RESULT")
})

test_that("NAME", {
  # tests for the property `NAME` (character)
  # Nom du port

  # uncomment below to test the property 
  #expect_equal(model.instance$`NAME`, "EXPECTED_RESULT")
})

test_that("MCA_CODE", {
  # tests for the property `MCA_CODE` (character)
  # Code MCA du port

  # uncomment below to test the property 
  #expect_equal(model.instance$`MCA_CODE`, "EXPECTED_RESULT")
})

test_that("MCA_NAME", {
  # tests for the property `MCA_NAME` (character)
  # Nom MCA du port

  # uncomment below to test the property 
  #expect_equal(model.instance$`MCA_NAME`, "EXPECTED_RESULT")
})

