# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DatafilesApi")

api.instance <- DatafilesApi$new()

test_that("ExportCsvMillesimeDatafile", {
  # tests for ExportCsvMillesimeDatafile
  # base path: https://data.statistiques.developpement-durable.gouv.fr/dido/api
  # Export csv d&#39;un milléime de fichier de données
  # Permet d&#39;obtenir un export csv d&#39;un millésime de fichier de données.              Il est possible de trier, filtrer et sélectionner les colonnes souhaitées.              Il existe une apidoc dédiée à chaque millésime où les paramètres de tri, de sélection de colonnes et de tri spécifique au millésime sont détaillés:              https://data.statistiques.developpement-durable.gouv.fr/dido/api/v1/datafiles/{rid}/millesime&#x3D;{millesime}/apidoc.html
  # @param rid character Identifiant du fichier de données.
  # @param with.column.name character faut-il ajouter le nom des colonnes en entête du fichier csv ?
  # @param with.column.description character faut-il ajouter la description des colonnes en entête du fichier csv ?
  # @param with.column.unit character faut-il ajouter l'unité des colonnes en entête du fichier csv ?
  # @param millesime character Millésime du fichier de données (le dernier millésime sera retournée si valeur omise) - format YYYY-MM (optional)
  # @param order.by array[character] Options de tri.       Les différents champs doivent être séparés par une virgule. Si il s'agit d'un tri descendant, il faut rajouter - devant.       Par exemple pour un fichier ayant les entêtes colonne1 et colonne2, une valeur pourrait être \"-colonne1,colonne2' pour trier d'abord par entete1 de manière décroissante puis par entete2 de manière croissante (optional)
  # @param columns array[character] Les colonnes à récupérer.       Les colonnes à récupérer séparées par une virgule. Par exemple \"colonne,colonne2\" pour récupérer uniquement les colonnes entete1 et entete2. (optional)
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ExportGeojsonMillesimeDatafile", {
  # tests for ExportGeojsonMillesimeDatafile
  # base path: https://data.statistiques.developpement-durable.gouv.fr/dido/api
  # Export geojson d&#39;un milléime de fichier de données
  # Permet d&#39;obtenir un export geojson d&#39;un millésime de fichier de données.              Cette route n&#39;existe que pour les fichiers de données qui utilisent un référentiel géographique.             Il est possible de trier, filtrer et sélectionner les colonnes souhaitées.              Il existe une apidoc dédiée à chaque millésime où les paramètres de tri, de sélection de colonnes et de tri spécifique au millésime sont détaillés:              https://data.statistiques.developpement-durable.gouv.fr/dido/api/v1/datafiles/{rid}/millesime&#x3D;{millesime}/apidoc.html
  # @param rid character Identifiant du fichier de données.
  # @param geo.field character Champ pivot pour la génération du geojson ou du shapefile
  # @param millesime character Millésime du fichier de données (le dernier millésime sera retournée si valeur omise) - format YYYY-MM (optional)
  # @param order.by array[character] Options de tri.       Les différents champs doivent être séparés par une virgule. Si il s'agit d'un tri descendant, il faut rajouter - devant.       Par exemple pour un fichier ayant les entêtes colonne1 et colonne2, une valeur pourrait être \"-colonne1,colonne2' pour trier d'abord par entete1 de manière décroissante puis par entete2 de manière croissante (optional)
  # @param columns array[character] Les colonnes à récupérer.       Les colonnes à récupérer séparées par une virgule. Par exemple \"colonne,colonne2\" pour récupérer uniquement les colonnes entete1 et entete2. (optional)
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ExportJsonMillesimeDatafile", {
  # tests for ExportJsonMillesimeDatafile
  # base path: https://data.statistiques.developpement-durable.gouv.fr/dido/api
  # Export json d&#39;un milléime de fichier de données
  # Permet d&#39;obtenir un export json d&#39;un millésime de fichier de données.              Il est possible de trier, filtrer et sélectionner les colonnes souhaitées.              Il existe une apidoc dédiée à chaque millésime où les paramètres de tri, de sélection de colonnes et de tri spécifique au millésime sont détaillés:              https://data.statistiques.developpement-durable.gouv.fr/dido/api/v1/datafiles/{rid}/millesime&#x3D;{millesime}/apidoc.html
  # @param rid character Identifiant du fichier de données.
  # @param millesime character Millésime du fichier de données (le dernier millésime sera retournée si valeur omise) - format YYYY-MM (optional)
  # @param order.by array[character] Options de tri.       Les différents champs doivent être séparés par une virgule. Si il s'agit d'un tri descendant, il faut rajouter - devant.       Par exemple pour un fichier ayant les entêtes colonne1 et colonne2, une valeur pourrait être \"-colonne1,colonne2' pour trier d'abord par entete1 de manière décroissante puis par entete2 de manière croissante (optional)
  # @param columns array[character] Les colonnes à récupérer.       Les colonnes à récupérer séparées par une virgule. Par exemple \"colonne,colonne2\" pour récupérer uniquement les colonnes entete1 et entete2. (optional)
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ExportShapefileMillesimeDatafile", {
  # tests for ExportShapefileMillesimeDatafile
  # base path: https://data.statistiques.developpement-durable.gouv.fr/dido/api
  # Export shapefile d&#39;un milléime de fichier de données
  # Permet d&#39;obtenir un export shapefile d&#39;un millésime de fichier de données.              Cette route n&#39;existe que pour les fichiers de données qui utilisent un référentiel géographique.             Il est possible de trier, filtrer et sélectionner les colonnes souhaitées.              Il existe une apidoc dédiée à chaque millésime où les paramètres de tri, de sélection de colonnes et de tri spécifique au millésime sont détaillés:              https://data.statistiques.developpement-durable.gouv.fr/dido/api/v1/datafiles/{rid}/millesime&#x3D;{millesime}/apidoc.html
  # @param rid character Identifiant du fichier de données.
  # @param geo.field character Champ pivot pour la génération du geojson ou du shapefile
  # @param millesime character Millésime du fichier de données (le dernier millésime sera retournée si valeur omise) - format YYYY-MM (optional)
  # @param order.by array[character] Options de tri.       Les différents champs doivent être séparés par une virgule. Si il s'agit d'un tri descendant, il faut rajouter - devant.       Par exemple pour un fichier ayant les entêtes colonne1 et colonne2, une valeur pourrait être \"-colonne1,colonne2' pour trier d'abord par entete1 de manière décroissante puis par entete2 de manière croissante (optional)
  # @param columns array[character] Les colonnes à récupérer.       Les colonnes à récupérer séparées par une virgule. Par exemple \"colonne,colonne2\" pour récupérer uniquement les colonnes entete1 et entete2. (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ExportXlsxMillesimeDatafile", {
  # tests for ExportXlsxMillesimeDatafile
  # base path: https://data.statistiques.developpement-durable.gouv.fr/dido/api
  # Export xlsx d&#39;un milléime de fichier de données
  # Permet d&#39;obtenir un export xlsx d&#39;un millésime de fichier de données.              Il est possible de trier, filtrer et sélectionner les colonnes souhaitées.              Il existe une apidoc dédiée à chaque millésime où les paramètres de tri, de sélection de colonnes et de tri spécifique au millésime sont détaillés:              https://data.statistiques.developpement-durable.gouv.fr/dido/api/v1/datafiles/{rid}/millesime&#x3D;{millesime}/apidoc.html
  # @param rid character Identifiant du fichier de données.
  # @param with.column.name character faut-il ajouter le nom des colonnes en entête du fichier csv ?
  # @param with.column.description character faut-il ajouter la description des colonnes en entête du fichier csv ?
  # @param with.column.unit character faut-il ajouter l'unité des colonnes en entête du fichier csv ?
  # @param millesime character Millésime du fichier de données (le dernier millésime sera retournée si valeur omise) - format YYYY-MM (optional)
  # @param order.by array[character] Options de tri.       Les différents champs doivent être séparés par une virgule. Si il s'agit d'un tri descendant, il faut rajouter - devant.       Par exemple pour un fichier ayant les entêtes colonne1 et colonne2, une valeur pourrait être \"-colonne1,colonne2' pour trier d'abord par entete1 de manière décroissante puis par entete2 de manière croissante (optional)
  # @param columns array[character] Les colonnes à récupérer.       Les colonnes à récupérer séparées par une virgule. Par exemple \"colonne,colonne2\" pour récupérer uniquement les colonnes entete1 et entete2. (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetMillesimeDatafile", {
  # tests for GetMillesimeDatafile
  # base path: https://data.statistiques.developpement-durable.gouv.fr/dido/api
  # Détail du millésime d&#39;un fichier de données (identifiée par son rid et son numéro de millésime -le dernier si le millésime n&#39;est pas saisi).
  # Permet d&#39;obtenir le détail d&#39;un fichier de données qui est identifié par son rid et son numéro de millésime. Si le numéro de millésime n&#39;est pas précisé, le dernier millésime du fichier de données est renvoyé.
  # @param rid character Identifiant du fichier de données.
  # @param millesime character Millésime du fichier de données (le dernier millésime sera retournée si valeur omise) - format YYYY-MM (optional)
  # @return [MillesimeDatafile]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PaginateDatafiles", {
  # tests for PaginateDatafiles
  # base path: https://data.statistiques.developpement-durable.gouv.fr/dido/api
  # Pagination des fichiers de données
  # Permet d&#39;obtenir une liste paginée des fichiers de données présents dans DiDo. Il est possible de spécifier le nombre de jeux de données à retourner, le numéro de la page à retourner et ajouter des critères de tri et de filtrage.
  # @param page integer Numéro de la page à afficher
  # @param page.size character Nombre de lignes par page
  # @param order.by array[character] Options de tri des fichiers de données (optional)
  # @param text character Texte à rechercher dans le titre ou la description du fichier de données (optional)
  # @return [PaginateListDatafiles]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PaginateMillesimeDatafile", {
  # tests for PaginateMillesimeDatafile
  # base path: https://data.statistiques.developpement-durable.gouv.fr/dido/api
  # Pagination des données d&#39;un millésime d&#39;un fichier de données
  # Permet d&#39;obtenir une liste paginée des données d&#39;un millésime de fichier de données.              Il est possible de trier, filtrer et sélectionner les colonnes souhaitées.              Il existe une apidoc dédiée à chaque millésime où les paramètres de tri, de sélection de colonnes et de tri spécifique au millésime sont détaillés:              https://data.statistiques.developpement-durable.gouv.fr/dido/api/v1/datafiles/{rid}/millesime&#x3D;{millesime}/apidoc.html
  # @param rid character Identifiant du fichier de données.
  # @param page integer Numéro de la page à afficher
  # @param page.size character Nombre de lignes par page
  # @param millesime character Millésime du fichier de données (le dernier millésime sera retournée si valeur omise) - format YYYY-MM (optional)
  # @param order.by array[character] Options de tri.       Les différents champs doivent être séparés par une virgule. Si il s'agit d'un tri descendant, il faut rajouter - devant.       Par exemple pour un fichier ayant les entêtes colonne1 et colonne2, une valeur pourrait être \"-colonne1,colonne2' pour trier d'abord par entete1 de manière décroissante puis par entete2 de manière croissante (optional)
  # @param columns array[character] Les colonnes à récupérer.       Les colonnes à récupérer séparées par une virgule. Par exemple \"colonne,colonne2\" pour récupérer uniquement les colonnes entete1 et entete2. (optional)
  # @return [PaginateListRows]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

