# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ItemStationsAir")

model.instance <- ItemStationsAir$new()

test_that("CODE", {
  # tests for the property `CODE` (character)
  # Code de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE`, "EXPECTED_RESULT")
})

test_that("NAME", {
  # tests for the property `NAME` (character)
  # Nom de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`NAME`, "EXPECTED_RESULT")
})

test_that("CODE_ZAS", {
  # tests for the property `CODE_ZAS` (character)
  # Code ZAS de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE_ZAS`, "EXPECTED_RESULT")
})

test_that("NAME_ZAS", {
  # tests for the property `NAME_ZAS` (character)
  # Nom ZAS de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`NAME_ZAS`, "EXPECTED_RESULT")
})

test_that("COMMUNE", {
  # tests for the property `COMMUNE` (character)
  # Commune de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`COMMUNE`, "EXPECTED_RESULT")
})

test_that("AASQA", {
  # tests for the property `AASQA` (character)
  # AASQA de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`AASQA`, "EXPECTED_RESULT")
})

test_that("LONGITUDE", {
  # tests for the property `LONGITUDE` (numeric)
  # Longitude de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`LONGITUDE`, "EXPECTED_RESULT")
})

test_that("LATITUDE", {
  # tests for the property `LATITUDE` (numeric)
  # Latitude de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`LATITUDE`, "EXPECTED_RESULT")
})

test_that("ALTITUDE", {
  # tests for the property `ALTITUDE` (numeric)
  # Altitude de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`ALTITUDE`, "EXPECTED_RESULT")
})

test_that("VALIDITY_START", {
  # tests for the property `VALIDITY_START` (character)
  # Début de la date de validité de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`VALIDITY_START`, "EXPECTED_RESULT")
})

test_that("VALIDITY_END", {
  # tests for the property `VALIDITY_END` (character)
  # Fin de la date de validité de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`VALIDITY_END`, "EXPECTED_RESULT")
})

test_that("SECTOR_TYPE", {
  # tests for the property `SECTOR_TYPE` (character)
  # Type de secteur de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`SECTOR_TYPE`, "EXPECTED_RESULT")
})

test_that("MILLESIME", {
  # tests for the property `MILLESIME` (numeric)
  # Millésime de la station

  # uncomment below to test the property 
  #expect_equal(model.instance$`MILLESIME`, "EXPECTED_RESULT")
})

test_that("IMPACT_PM10", {
  # tests for the property `IMPACT_PM10` (character)
  # Impact PM10

  # uncomment below to test the property 
  #expect_equal(model.instance$`IMPACT_PM10`, "EXPECTED_RESULT")
})

test_that("IMPACT_NO2", {
  # tests for the property `IMPACT_NO2` (character)
  # Impact NO2

  # uncomment below to test the property 
  #expect_equal(model.instance$`IMPACT_NO2`, "EXPECTED_RESULT")
})

test_that("IMPACT_O3", {
  # tests for the property `IMPACT_O3` (character)
  # IMpact O3

  # uncomment below to test the property 
  #expect_equal(model.instance$`IMPACT_O3`, "EXPECTED_RESULT")
})

test_that("IMPACT_SO2", {
  # tests for the property `IMPACT_SO2` (character)
  # Impact SO2

  # uncomment below to test the property 
  #expect_equal(model.instance$`IMPACT_SO2`, "EXPECTED_RESULT")
})

test_that("IMPACT_PM25", {
  # tests for the property `IMPACT_PM25` (character)
  # Impact PM25

  # uncomment below to test the property 
  #expect_equal(model.instance$`IMPACT_PM25`, "EXPECTED_RESULT")
})

test_that("IMPACT_CO", {
  # tests for the property `IMPACT_CO` (character)
  # Impact CO

  # uncomment below to test the property 
  #expect_equal(model.instance$`IMPACT_CO`, "EXPECTED_RESULT")
})

