# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PaginateListBilanEnergie")

model.instance <- PaginateListBilanEnergie$new()

test_that("pageSize", {
  # tests for the property `pageSize` (character)
  # le nombre de lignes dans la page

  # uncomment below to test the property 
  #expect_equal(model.instance$`pageSize`, "EXPECTED_RESULT")
})

test_that("page", {
  # tests for the property `page` (integer)
  # le numéro de la page actuelle

  # uncomment below to test the property 
  #expect_equal(model.instance$`page`, "EXPECTED_RESULT")
})

test_that("total", {
  # tests for the property `total` (integer)
  # le nombre total de lignes

  # uncomment below to test the property 
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("firstPage", {
  # tests for the property `firstPage` (character)
  # le lien vers la première page

  # uncomment below to test the property 
  #expect_equal(model.instance$`firstPage`, "EXPECTED_RESULT")
})

test_that("previousPage", {
  # tests for the property `previousPage` (character)
  # le lien vers la page précédente

  # uncomment below to test the property 
  #expect_equal(model.instance$`previousPage`, "EXPECTED_RESULT")
})

test_that("nextPage", {
  # tests for the property `nextPage` (character)
  # le lien vers la page suivante

  # uncomment below to test the property 
  #expect_equal(model.instance$`nextPage`, "EXPECTED_RESULT")
})

test_that("lastPage", {
  # tests for the property `lastPage` (character)
  # le lien vers la dernière page

  # uncomment below to test the property 
  #expect_equal(model.instance$`lastPage`, "EXPECTED_RESULT")
})

test_that("data", {
  # tests for the property `data` (array[ItemBilanEnergie])

  # uncomment below to test the property 
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

