# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MillesimeDatafileAllOf")

model.instance <- MillesimeDatafileAllOf$new()

test_that("rows", {
  # tests for the property `rows` (integer)
  # Nombre de lignes dans le fichier de données

  # uncomment below to test the property 
  #expect_equal(model.instance$`rows`, "EXPECTED_RESULT")
})

test_that("columns", {
  # tests for the property `columns` (array[DatafileSimpleColumns])
  # Liste des colonnes du fichier de données

  # uncomment below to test the property 
  #expect_equal(model.instance$`columns`, "EXPECTED_RESULT")
})

test_that("extendedFilters", {
  # tests for the property `extendedFilters` (array[DatafileSimpleExtendedFilters])
  # Liste des filtres étendus du fichier de données

  # uncomment below to test the property 
  #expect_equal(model.instance$`extendedFilters`, "EXPECTED_RESULT")
})

test_that("geoFields", {
  # tests for the property `geoFields` (array[character])
  # Liste des champs disposant d&#39;une géométrie dans le fichier de données

  # uncomment below to test the property 
  #expect_equal(model.instance$`geoFields`, "EXPECTED_RESULT")
})

