# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Attachment")

model.instance <- Attachment$new()

test_that("rid", {
  # tests for the property `rid` (character)
  # Identifiant du fichier descriptif

  # uncomment below to test the property 
  #expect_equal(model.instance$`rid`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)
  # Titre du fichier descriptif

  # uncomment below to test the property 
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description du fichier descriptif

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("published", {
  # tests for the property `published` (character)
  # Date de publication du fichier descriptif - format iso 8601

  # uncomment below to test the property 
  #expect_equal(model.instance$`published`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)
  # Url pour accéder au fichier descriptif

  # uncomment below to test the property 
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

test_that("created_at", {
  # tests for the property `created_at` (character)
  # Date de création du fichier de données - format iso 8601

  # uncomment below to test the property 
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("last_modified", {
  # tests for the property `last_modified` (character)
  # Date de dernière modification du fichier de données - format iso 8601

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_modified`, "EXPECTED_RESULT")
})

