# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ItemTags")

model.instance <- ItemTags$new()

test_that("VALUE", {
  # tests for the property `VALUE` (character)
  # Valeur du mot-clé

  # uncomment below to test the property 
  #expect_equal(model.instance$`VALUE`, "EXPECTED_RESULT")
})

test_that("DISPLAY", {
  # tests for the property `DISPLAY` (character)
  # Valeur d&#39;affichage du mot-clé

  # uncomment below to test the property 
  #expect_equal(model.instance$`DISPLAY`, "EXPECTED_RESULT")
})

test_that("TOPICS", {
  # tests for the property `TOPICS` (character)
  # Thèmes auxquels appartient le mot-clé

  # uncomment below to test the property 
  #expect_equal(model.instance$`TOPICS`, "EXPECTED_RESULT")
})

test_that("EUROVOC", {
  # tests for the property `EUROVOC` (character)
  # Valeur eurovoc du mot-clé

  # uncomment below to test the property 
  #expect_equal(model.instance$`EUROVOC`, "EXPECTED_RESULT")
})

test_that("ECOPLANET", {
  # tests for the property `ECOPLANET` (character)
  # Valeur ecoplanet du mot-clé

  # uncomment below to test the property 
  #expect_equal(model.instance$`ECOPLANET`, "EXPECTED_RESULT")
})

