# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ItemGeozones")

model.instance <- ItemGeozones$new()

test_that("ID", {
  # tests for the property `ID` (character)
  # Identifiant de la geozone

  # uncomment below to test the property 
  #expect_equal(model.instance$`ID`, "EXPECTED_RESULT")
})

test_that("LEVEL", {
  # tests for the property `LEVEL` (character)
  # Niveau géographique de la geozone

  # uncomment below to test the property 
  #expect_equal(model.instance$`LEVEL`, "EXPECTED_RESULT")
})

test_that("CODE", {
  # tests for the property `CODE` (character)
  # Code de la geozone

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE`, "EXPECTED_RESULT")
})

test_that("VALIDITY_START", {
  # tests for the property `VALIDITY_START` (character)
  # Début de la date de validité de la geozone

  # uncomment below to test the property 
  #expect_equal(model.instance$`VALIDITY_START`, "EXPECTED_RESULT")
})

test_that("VALIDITY_END", {
  # tests for the property `VALIDITY_END` (character)
  # Fin de la date de validité de la geonzone

  # uncomment below to test the property 
  #expect_equal(model.instance$`VALIDITY_END`, "EXPECTED_RESULT")
})

test_that("NAME", {
  # tests for the property `NAME` (character)
  # Nom officiel de la geozone

  # uncomment below to test the property 
  #expect_equal(model.instance$`NAME`, "EXPECTED_RESULT")
})

