# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DatafileFull")

model.instance <- DatafileFull$new()

test_that("rid", {
  # tests for the property `rid` (character)
  # Identifiant du fichier de données

  # uncomment below to test the property 
  #expect_equal(model.instance$`rid`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)
  # Titre du fichier de données

  # uncomment below to test the property 
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description du fichier de données

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("published", {
  # tests for the property `published` (character)
  # Date de publication du fichier de données - format iso 8601

  # uncomment below to test the property 
  #expect_equal(model.instance$`published`, "EXPECTED_RESULT")
})

test_that("temporal_coverage", {
  # tests for the property `temporal_coverage` (DatafileSimpleTemporalCoverage)

  # uncomment below to test the property 
  #expect_equal(model.instance$`temporal_coverage`, "EXPECTED_RESULT")
})

test_that("legal_notice", {
  # tests for the property `legal_notice` (character)
  # Notice légale concernant le fichier de données

  # uncomment below to test the property 
  #expect_equal(model.instance$`legal_notice`, "EXPECTED_RESULT")
})

test_that("weburl", {
  # tests for the property `weburl` (character)
  # Url pour accéder à l&#39;interface de visualisation du fichier de données

  # uncomment below to test the property 
  #expect_equal(model.instance$`weburl`, "EXPECTED_RESULT")
})

test_that("millesimes", {
  # tests for the property `millesimes` (array[DatafileSimpleMillesimes])
  # Informations sur les millésimes du fichier de données

  # uncomment below to test the property 
  #expect_equal(model.instance$`millesimes`, "EXPECTED_RESULT")
})

test_that("created_at", {
  # tests for the property `created_at` (character)
  # date de création du fichier de données - format iso 8601

  # uncomment below to test the property 
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("last_modified", {
  # tests for the property `last_modified` (character)
  # Date de dernière modification du fichier de données - format iso 8601

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_modified`, "EXPECTED_RESULT")
})

test_that("dataset", {
  # tests for the property `dataset` (DatasetSimple)

  # uncomment below to test the property 
  #expect_equal(model.instance$`dataset`, "EXPECTED_RESULT")
})

