# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ItemPolluantsEau")

model.instance <- ItemPolluantsEau$new()

test_that("CODE", {
  # tests for the property `CODE` (character)
  # Code du polluant

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE`, "EXPECTED_RESULT")
})

test_that("NAME", {
  # tests for the property `NAME` (character)
  # Nom du polluant

  # uncomment below to test the property 
  #expect_equal(model.instance$`NAME`, "EXPECTED_RESULT")
})

test_that("UNIT", {
  # tests for the property `UNIT` (character)
  # Unité du polluant

  # uncomment below to test the property 
  #expect_equal(model.instance$`UNIT`, "EXPECTED_RESULT")
})

