# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ItemCog")

model.instance <- ItemCog$new()

test_that("ID", {
  # tests for the property `ID` (character)
  # Identifiant de la zone

  # uncomment below to test the property 
  #expect_equal(model.instance$`ID`, "EXPECTED_RESULT")
})

test_that("MILLESIME", {
  # tests for the property `MILLESIME` (integer)
  # Millésime de la zone

  # uncomment below to test the property 
  #expect_equal(model.instance$`MILLESIME`, "EXPECTED_RESULT")
})

test_that("TYPE", {
  # tests for the property `TYPE` (character)
  # Type de la zone

  # uncomment below to test the property 
  #expect_equal(model.instance$`TYPE`, "EXPECTED_RESULT")
})

test_that("LEVEL", {
  # tests for the property `LEVEL` (character)
  # Niveau géographique de la zone

  # uncomment below to test the property 
  #expect_equal(model.instance$`LEVEL`, "EXPECTED_RESULT")
})

test_that("CODE_MILLESIME", {
  # tests for the property `CODE_MILLESIME` (character)
  # Code de la zone dans le millésime

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE_MILLESIME`, "EXPECTED_RESULT")
})

test_that("CODE_CURRENT", {
  # tests for the property `CODE_CURRENT` (character)
  # Code actuel de la zone

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE_CURRENT`, "EXPECTED_RESULT")
})

test_that("OFFICIAL_NAME", {
  # tests for the property `OFFICIAL_NAME` (character)
  # Nom officiel de la zone

  # uncomment below to test the property 
  #expect_equal(model.instance$`OFFICIAL_NAME`, "EXPECTED_RESULT")
})

test_that("UPPER_NAME", {
  # tests for the property `UPPER_NAME` (character)
  # Nom de la zone en majuscule

  # uncomment below to test the property 
  #expect_equal(model.instance$`UPPER_NAME`, "EXPECTED_RESULT")
})

test_that("LOWER_NAME", {
  # tests for the property `LOWER_NAME` (character)
  # Nom la zone en miniscule

  # uncomment below to test the property 
  #expect_equal(model.instance$`LOWER_NAME`, "EXPECTED_RESULT")
})

test_that("LONGITUDE", {
  # tests for the property `LONGITUDE` (numeric)
  # Latitude de la zone

  # uncomment below to test the property 
  #expect_equal(model.instance$`LONGITUDE`, "EXPECTED_RESULT")
})

test_that("LATITUDE", {
  # tests for the property `LATITUDE` (numeric)
  # Longitude de la zone

  # uncomment below to test the property 
  #expect_equal(model.instance$`LATITUDE`, "EXPECTED_RESULT")
})

