# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ItemCslOperations")

model.instance <- ItemCslOperations$new()

test_that("CODE_1", {
  # tests for the property `CODE_1` (character)
  # Code de l&#39;opération niveau 1

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE_1`, "EXPECTED_RESULT")
})

test_that("NAME_1", {
  # tests for the property `NAME_1` (character)
  # Nom de l&#39;opération niveau 1

  # uncomment below to test the property 
  #expect_equal(model.instance$`NAME_1`, "EXPECTED_RESULT")
})

test_that("CODE_2", {
  # tests for the property `CODE_2` (character)
  # Code de l&#39;opération niveau 2

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE_2`, "EXPECTED_RESULT")
})

test_that("NAME_2", {
  # tests for the property `NAME_2` (character)
  # Nom de l&#39;opération niveau 2

  # uncomment below to test the property 
  #expect_equal(model.instance$`NAME_2`, "EXPECTED_RESULT")
})

test_that("CODE_3", {
  # tests for the property `CODE_3` (character)
  # Code de l&#39;opération niveau 3

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE_3`, "EXPECTED_RESULT")
})

test_that("NAME_3", {
  # tests for the property `NAME_3` (character)
  # Nom de l&#39;opération niveau 3

  # uncomment below to test the property 
  #expect_equal(model.instance$`NAME_3`, "EXPECTED_RESULT")
})

test_that("CODE_4", {
  # tests for the property `CODE_4` (character)
  # Code de l&#39;opération niveau 4

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE_4`, "EXPECTED_RESULT")
})

test_that("NAME_4", {
  # tests for the property `NAME_4` (character)
  # Nom de l&#39;opération niveau 4

  # uncomment below to test the property 
  #expect_equal(model.instance$`NAME_4`, "EXPECTED_RESULT")
})

