# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ItemCslFilieres")

model.instance <- ItemCslFilieres$new()

test_that("CODE", {
  # tests for the property `CODE` (character)
  # Code de la filière

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE`, "EXPECTED_RESULT")
})

test_that("NAME", {
  # tests for the property `NAME` (character)
  # Nom de la filière

  # uncomment below to test the property 
  #expect_equal(model.instance$`NAME`, "EXPECTED_RESULT")
})

