# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DatafileSimpleColumns")

model.instance <- DatafileSimpleColumns$new()

test_that("name", {
  # tests for the property `name` (character)
  # Nom de la colonne

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description de la colonne

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("unit", {
  # tests for the property `unit` (character)
  # Unité de la colonne

  # uncomment below to test the property 
  #expect_equal(model.instance$`unit`, "EXPECTED_RESULT")
})

test_that("filters", {
  # tests for the property `filters` (array[character])
  # Liste des filtres disponibles pour cette colonne. Dépend de la colonne.

  # uncomment below to test the property 
  #expect_equal(model.instance$`filters`, "EXPECTED_RESULT")
})

