# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ItemBilanEnergie")

model.instance <- ItemBilanEnergie$new()

test_that("CODE", {
  # tests for the property `CODE` (character)
  # Code

  # uncomment below to test the property 
  #expect_equal(model.instance$`CODE`, "EXPECTED_RESULT")
})

test_that("NAME", {
  # tests for the property `NAME` (character)
  # Nom

  # uncomment below to test the property 
  #expect_equal(model.instance$`NAME`, "EXPECTED_RESULT")
})

test_that("UNIT", {
  # tests for the property `UNIT` (character)
  # Unité

  # uncomment below to test the property 
  #expect_equal(model.instance$`UNIT`, "EXPECTED_RESULT")
})

test_that("LEVEL", {
  # tests for the property `LEVEL` (character)
  # Level

  # uncomment below to test the property 
  #expect_equal(model.instance$`LEVEL`, "EXPECTED_RESULT")
})

test_that("DATA_TYPE", {
  # tests for the property `DATA_TYPE` (character)
  # Type de données

  # uncomment below to test the property 
  #expect_equal(model.instance$`DATA_TYPE`, "EXPECTED_RESULT")
})

test_that("FLOW_TYPE", {
  # tests for the property `FLOW_TYPE` (character)
  # Type de flux

  # uncomment below to test the property 
  #expect_equal(model.instance$`FLOW_TYPE`, "EXPECTED_RESULT")
})

