# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PaginateListRowsAllOf")

model.instance <- PaginateListRowsAllOf$new()

test_that("data", {
  # tests for the property `data` (array[object])
  # Les lignes correspondant aux critères

  # uncomment below to test the property 
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

