# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DatafileFullAllOf")

model.instance <- DatafileFullAllOf$new()

test_that("dataset", {
  # tests for the property `dataset` (DatasetSimple)

  # uncomment below to test the property 
  #expect_equal(model.instance$`dataset`, "EXPECTED_RESULT")
})

