# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ServerError")

model.instance <- ServerError$new()

test_that("code", {
  # tests for the property `code` (integer)
  # le code HTTP de l&#39;erreur

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)
  # le message de l&#39;erreur

  # uncomment below to test the property 
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

