# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DatafileSimpleTemporalCoverage")

model.instance <- DatafileSimpleTemporalCoverage$new()

test_that("start", {
  # tests for the property `start` (character)
  # Date de début de la couverture temporelle du fichier de données - format YYYY-MM-DD

  # uncomment below to test the property 
  #expect_equal(model.instance$`start`, "EXPECTED_RESULT")
})

test_that("end", {
  # tests for the property `end` (character)
  # Date de fin de la couverture temporelle du fichier de données - format YYYY-MM-DD

  # uncomment below to test the property 
  #expect_equal(model.instance$`end`, "EXPECTED_RESULT")
})

