# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PaginateListPolluantsEauAllOf")

model.instance <- PaginateListPolluantsEauAllOf$new()

test_that("data", {
  # tests for the property `data` (array[ItemPolluantsEau])

  # uncomment below to test the property 
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

