# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PaginateListCslFilieresAllOf")

model.instance <- PaginateListCslFilieresAllOf$new()

test_that("data", {
  # tests for the property `data` (array[ItemCslFilieres])

  # uncomment below to test the property 
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

