# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Attachment
#'
#' @description Attachment Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field rid  character 
#'
#' @field title  character 
#'
#' @field description  character 
#'
#' @field published  character 
#'
#' @field url  character 
#'
#' @field created_at  character 
#'
#' @field last_modified  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Attachment <- R6::R6Class(
  'Attachment',
  public = list(
    `rid` = NULL,
    `title` = NULL,
    `description` = NULL,
    `published` = NULL,
    `url` = NULL,
    `created_at` = NULL,
    `last_modified` = NULL,
    initialize = function(
        `rid`, `title`, `description`, `published`, `url`, `created_at`, `last_modified`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`rid`)) {
        stopifnot(is.character(`rid`), length(`rid`) == 1)
        self$`rid` <- `rid`
      }
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`published`)) {
        stopifnot(is.character(`published`), length(`published`) == 1)
        self$`published` <- `published`
      }
      if (!missing(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
      if (!missing(`created_at`)) {
        stopifnot(is.character(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!is.null(`last_modified`)) {
        stopifnot(is.character(`last_modified`), length(`last_modified`) == 1)
        self$`last_modified` <- `last_modified`
      }
    },
    toJSON = function() {
      AttachmentObject <- list()
      if (!is.null(self$`rid`)) {
        AttachmentObject[['rid']] <-
          self$`rid`
      }
      if (!is.null(self$`title`)) {
        AttachmentObject[['title']] <-
          self$`title`
      }
      if (!is.null(self$`description`)) {
        AttachmentObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`published`)) {
        AttachmentObject[['published']] <-
          self$`published`
      }
      if (!is.null(self$`url`)) {
        AttachmentObject[['url']] <-
          self$`url`
      }
      if (!is.null(self$`created_at`)) {
        AttachmentObject[['created_at']] <-
          self$`created_at`
      }
      if (!is.null(self$`last_modified`)) {
        AttachmentObject[['last_modified']] <-
          self$`last_modified`
      }

      AttachmentObject
    },
    fromJSON = function(AttachmentJson) {
      AttachmentObject <- jsonlite::fromJSON(AttachmentJson)
      if (!is.null(AttachmentObject$`rid`)) {
        self$`rid` <- AttachmentObject$`rid`
      }
      if (!is.null(AttachmentObject$`title`)) {
        self$`title` <- AttachmentObject$`title`
      }
      if (!is.null(AttachmentObject$`description`)) {
        self$`description` <- AttachmentObject$`description`
      }
      if (!is.null(AttachmentObject$`published`)) {
        self$`published` <- AttachmentObject$`published`
      }
      if (!is.null(AttachmentObject$`url`)) {
        self$`url` <- AttachmentObject$`url`
      }
      if (!is.null(AttachmentObject$`created_at`)) {
        self$`created_at` <- AttachmentObject$`created_at`
      }
      if (!is.null(AttachmentObject$`last_modified`)) {
        self$`last_modified` <- AttachmentObject$`last_modified`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`rid`)) {
        sprintf(
        '"rid":
          "%s"
                ',
        self$`rid`
        )},
        if (!is.null(self$`title`)) {
        sprintf(
        '"title":
          "%s"
                ',
        self$`title`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`published`)) {
        sprintf(
        '"published":
          "%s"
                ',
        self$`published`
        )},
        if (!is.null(self$`url`)) {
        sprintf(
        '"url":
          "%s"
                ',
        self$`url`
        )},
        if (!is.null(self$`created_at`)) {
        sprintf(
        '"created_at":
          "%s"
                ',
        self$`created_at`
        )},
        if (!is.null(self$`last_modified`)) {
        sprintf(
        '"last_modified":
          "%s"
                ',
        self$`last_modified`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AttachmentJson) {
      AttachmentObject <- jsonlite::fromJSON(AttachmentJson)
      self$`rid` <- AttachmentObject$`rid`
      self$`title` <- AttachmentObject$`title`
      self$`description` <- AttachmentObject$`description`
      self$`published` <- AttachmentObject$`published`
      self$`url` <- AttachmentObject$`url`
      self$`created_at` <- AttachmentObject$`created_at`
      self$`last_modified` <- AttachmentObject$`last_modified`
      self
    }
  )
)
