# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DatafileSimpleColumns
#'
#' @description DatafileSimpleColumns Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character 
#'
#' @field description  character 
#'
#' @field unit  character 
#'
#' @field filters  list( character ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DatafileSimpleColumns <- R6::R6Class(
  'DatafileSimpleColumns',
  public = list(
    `name` = NULL,
    `description` = NULL,
    `unit` = NULL,
    `filters` = NULL,
    initialize = function(
        `name`, `description`, `unit`, `filters`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`unit`)) {
        stopifnot(is.character(`unit`), length(`unit`) == 1)
        self$`unit` <- `unit`
      }
      if (!missing(`filters`)) {
        stopifnot(is.vector(`filters`), length(`filters`) != 0)
        sapply(`filters`, function(x) stopifnot(is.character(x)))
        self$`filters` <- `filters`
      }
    },
    toJSON = function() {
      DatafileSimpleColumnsObject <- list()
      if (!is.null(self$`name`)) {
        DatafileSimpleColumnsObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`description`)) {
        DatafileSimpleColumnsObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`unit`)) {
        DatafileSimpleColumnsObject[['unit']] <-
          self$`unit`
      }
      if (!is.null(self$`filters`)) {
        DatafileSimpleColumnsObject[['filters']] <-
          self$`filters`
      }

      DatafileSimpleColumnsObject
    },
    fromJSON = function(DatafileSimpleColumnsJson) {
      DatafileSimpleColumnsObject <- jsonlite::fromJSON(DatafileSimpleColumnsJson)
      if (!is.null(DatafileSimpleColumnsObject$`name`)) {
        self$`name` <- DatafileSimpleColumnsObject$`name`
      }
      if (!is.null(DatafileSimpleColumnsObject$`description`)) {
        self$`description` <- DatafileSimpleColumnsObject$`description`
      }
      if (!is.null(DatafileSimpleColumnsObject$`unit`)) {
        self$`unit` <- DatafileSimpleColumnsObject$`unit`
      }
      if (!is.null(DatafileSimpleColumnsObject$`filters`)) {
        self$`filters` <- ApiClient$new()$deserializeObj(DatafileSimpleColumnsObject$`filters`, "array[character]", loadNamespace("didoscalie"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`unit`)) {
        sprintf(
        '"unit":
          "%s"
                ',
        self$`unit`
        )},
        if (!is.null(self$`filters`)) {
        sprintf(
        '"filters":
           [%s]
        ',
        paste(unlist(lapply(self$`filters`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DatafileSimpleColumnsJson) {
      DatafileSimpleColumnsObject <- jsonlite::fromJSON(DatafileSimpleColumnsJson)
      self$`name` <- DatafileSimpleColumnsObject$`name`
      self$`description` <- DatafileSimpleColumnsObject$`description`
      self$`unit` <- DatafileSimpleColumnsObject$`unit`
      self$`filters` <- ApiClient$new()$deserializeObj(DatafileSimpleColumnsObject$`filters`, "array[character]", loadNamespace("didoscalie"))
      self
    }
  )
)
