# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DatafileSimpleExtendedFilters
#'
#' @description DatafileSimpleExtendedFilters Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character 
#'
#' @field columns  list( character ) 
#'
#' @field filters  list( character ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DatafileSimpleExtendedFilters <- R6::R6Class(
  'DatafileSimpleExtendedFilters',
  public = list(
    `name` = NULL,
    `columns` = NULL,
    `filters` = NULL,
    initialize = function(
        `name`, `columns`, `filters`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`columns`)) {
        stopifnot(is.vector(`columns`), length(`columns`) != 0)
        sapply(`columns`, function(x) stopifnot(is.character(x)))
        self$`columns` <- `columns`
      }
      if (!missing(`filters`)) {
        stopifnot(is.vector(`filters`), length(`filters`) != 0)
        sapply(`filters`, function(x) stopifnot(is.character(x)))
        self$`filters` <- `filters`
      }
    },
    toJSON = function() {
      DatafileSimpleExtendedFiltersObject <- list()
      if (!is.null(self$`name`)) {
        DatafileSimpleExtendedFiltersObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`columns`)) {
        DatafileSimpleExtendedFiltersObject[['columns']] <-
          self$`columns`
      }
      if (!is.null(self$`filters`)) {
        DatafileSimpleExtendedFiltersObject[['filters']] <-
          self$`filters`
      }

      DatafileSimpleExtendedFiltersObject
    },
    fromJSON = function(DatafileSimpleExtendedFiltersJson) {
      DatafileSimpleExtendedFiltersObject <- jsonlite::fromJSON(DatafileSimpleExtendedFiltersJson)
      if (!is.null(DatafileSimpleExtendedFiltersObject$`name`)) {
        self$`name` <- DatafileSimpleExtendedFiltersObject$`name`
      }
      if (!is.null(DatafileSimpleExtendedFiltersObject$`columns`)) {
        self$`columns` <- ApiClient$new()$deserializeObj(DatafileSimpleExtendedFiltersObject$`columns`, "array[character]", loadNamespace("didoscalie"))
      }
      if (!is.null(DatafileSimpleExtendedFiltersObject$`filters`)) {
        self$`filters` <- ApiClient$new()$deserializeObj(DatafileSimpleExtendedFiltersObject$`filters`, "array[character]", loadNamespace("didoscalie"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`columns`)) {
        sprintf(
        '"columns":
           [%s]
        ',
        paste(unlist(lapply(self$`columns`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`filters`)) {
        sprintf(
        '"filters":
           [%s]
        ',
        paste(unlist(lapply(self$`filters`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DatafileSimpleExtendedFiltersJson) {
      DatafileSimpleExtendedFiltersObject <- jsonlite::fromJSON(DatafileSimpleExtendedFiltersJson)
      self$`name` <- DatafileSimpleExtendedFiltersObject$`name`
      self$`columns` <- ApiClient$new()$deserializeObj(DatafileSimpleExtendedFiltersObject$`columns`, "array[character]", loadNamespace("didoscalie"))
      self$`filters` <- ApiClient$new()$deserializeObj(DatafileSimpleExtendedFiltersObject$`filters`, "array[character]", loadNamespace("didoscalie"))
      self
    }
  )
)
