# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DatafileSimple
#'
#' @description DatafileSimple Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field rid  character 
#'
#' @field title  character 
#'
#' @field description  character 
#'
#' @field published  character 
#'
#' @field temporal_coverage  \link{DatafileSimpleTemporalCoverage} [optional]
#'
#' @field legal_notice  character [optional]
#'
#' @field weburl  character 
#'
#' @field millesimes  list( \link{DatafileSimpleMillesimes} ) 
#'
#' @field created_at  character 
#'
#' @field last_modified  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DatafileSimple <- R6::R6Class(
  'DatafileSimple',
  public = list(
    `rid` = NULL,
    `title` = NULL,
    `description` = NULL,
    `published` = NULL,
    `temporal_coverage` = NULL,
    `legal_notice` = NULL,
    `weburl` = NULL,
    `millesimes` = NULL,
    `created_at` = NULL,
    `last_modified` = NULL,
    initialize = function(
        `rid`, `title`, `description`, `published`, `weburl`, `millesimes`, `created_at`, `temporal_coverage`=NULL, `legal_notice`=NULL, `last_modified`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`rid`)) {
        stopifnot(is.character(`rid`), length(`rid`) == 1)
        self$`rid` <- `rid`
      }
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`published`)) {
        stopifnot(is.character(`published`), length(`published`) == 1)
        self$`published` <- `published`
      }
      if (!missing(`weburl`)) {
        stopifnot(is.character(`weburl`), length(`weburl`) == 1)
        self$`weburl` <- `weburl`
      }
      if (!missing(`millesimes`)) {
        stopifnot(is.vector(`millesimes`), length(`millesimes`) != 0)
        sapply(`millesimes`, function(x) stopifnot(R6::is.R6(x)))
        self$`millesimes` <- `millesimes`
      }
      if (!missing(`created_at`)) {
        stopifnot(is.character(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!is.null(`temporal_coverage`)) {
        stopifnot(R6::is.R6(`temporal_coverage`))
        self$`temporal_coverage` <- `temporal_coverage`
      }
      if (!is.null(`legal_notice`)) {
        stopifnot(is.character(`legal_notice`), length(`legal_notice`) == 1)
        self$`legal_notice` <- `legal_notice`
      }
      if (!is.null(`last_modified`)) {
        stopifnot(is.character(`last_modified`), length(`last_modified`) == 1)
        self$`last_modified` <- `last_modified`
      }
    },
    toJSON = function() {
      DatafileSimpleObject <- list()
      if (!is.null(self$`rid`)) {
        DatafileSimpleObject[['rid']] <-
          self$`rid`
      }
      if (!is.null(self$`title`)) {
        DatafileSimpleObject[['title']] <-
          self$`title`
      }
      if (!is.null(self$`description`)) {
        DatafileSimpleObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`published`)) {
        DatafileSimpleObject[['published']] <-
          self$`published`
      }
      if (!is.null(self$`temporal_coverage`)) {
        DatafileSimpleObject[['temporal_coverage']] <-
          self$`temporal_coverage`$toJSON()
      }
      if (!is.null(self$`legal_notice`)) {
        DatafileSimpleObject[['legal_notice']] <-
          self$`legal_notice`
      }
      if (!is.null(self$`weburl`)) {
        DatafileSimpleObject[['weburl']] <-
          self$`weburl`
      }
      if (!is.null(self$`millesimes`)) {
        DatafileSimpleObject[['millesimes']] <-
          lapply(self$`millesimes`, function(x) x$toJSON())
      }
      if (!is.null(self$`created_at`)) {
        DatafileSimpleObject[['created_at']] <-
          self$`created_at`
      }
      if (!is.null(self$`last_modified`)) {
        DatafileSimpleObject[['last_modified']] <-
          self$`last_modified`
      }

      DatafileSimpleObject
    },
    fromJSON = function(DatafileSimpleJson) {
      DatafileSimpleObject <- jsonlite::fromJSON(DatafileSimpleJson)
      if (!is.null(DatafileSimpleObject$`rid`)) {
        self$`rid` <- DatafileSimpleObject$`rid`
      }
      if (!is.null(DatafileSimpleObject$`title`)) {
        self$`title` <- DatafileSimpleObject$`title`
      }
      if (!is.null(DatafileSimpleObject$`description`)) {
        self$`description` <- DatafileSimpleObject$`description`
      }
      if (!is.null(DatafileSimpleObject$`published`)) {
        self$`published` <- DatafileSimpleObject$`published`
      }
      if (!is.null(DatafileSimpleObject$`temporal_coverage`)) {
        temporal_coverageObject <- DatafileSimpleTemporalCoverage$new()
        temporal_coverageObject$fromJSON(jsonlite::toJSON(DatafileSimpleObject$temporal_coverage, auto_unbox = TRUE, digits = NA))
        self$`temporal_coverage` <- temporal_coverageObject
      }
      if (!is.null(DatafileSimpleObject$`legal_notice`)) {
        self$`legal_notice` <- DatafileSimpleObject$`legal_notice`
      }
      if (!is.null(DatafileSimpleObject$`weburl`)) {
        self$`weburl` <- DatafileSimpleObject$`weburl`
      }
      if (!is.null(DatafileSimpleObject$`millesimes`)) {
        self$`millesimes` <- ApiClient$new()$deserializeObj(DatafileSimpleObject$`millesimes`, "array[DatafileSimpleMillesimes]", loadNamespace("didoscalie"))
      }
      if (!is.null(DatafileSimpleObject$`created_at`)) {
        self$`created_at` <- DatafileSimpleObject$`created_at`
      }
      if (!is.null(DatafileSimpleObject$`last_modified`)) {
        self$`last_modified` <- DatafileSimpleObject$`last_modified`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`rid`)) {
        sprintf(
        '"rid":
          "%s"
                ',
        self$`rid`
        )},
        if (!is.null(self$`title`)) {
        sprintf(
        '"title":
          "%s"
                ',
        self$`title`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`published`)) {
        sprintf(
        '"published":
          "%s"
                ',
        self$`published`
        )},
        if (!is.null(self$`temporal_coverage`)) {
        sprintf(
        '"temporal_coverage":
        %s
        ',
        jsonlite::toJSON(self$`temporal_coverage`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`legal_notice`)) {
        sprintf(
        '"legal_notice":
          "%s"
                ',
        self$`legal_notice`
        )},
        if (!is.null(self$`weburl`)) {
        sprintf(
        '"weburl":
          "%s"
                ',
        self$`weburl`
        )},
        if (!is.null(self$`millesimes`)) {
        sprintf(
        '"millesimes":
        [%s]
',
        paste(sapply(self$`millesimes`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`created_at`)) {
        sprintf(
        '"created_at":
          "%s"
                ',
        self$`created_at`
        )},
        if (!is.null(self$`last_modified`)) {
        sprintf(
        '"last_modified":
          "%s"
                ',
        self$`last_modified`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DatafileSimpleJson) {
      DatafileSimpleObject <- jsonlite::fromJSON(DatafileSimpleJson)
      self$`rid` <- DatafileSimpleObject$`rid`
      self$`title` <- DatafileSimpleObject$`title`
      self$`description` <- DatafileSimpleObject$`description`
      self$`published` <- DatafileSimpleObject$`published`
      self$`temporal_coverage` <- DatafileSimpleTemporalCoverage$new()$fromJSON(jsonlite::toJSON(DatafileSimpleObject$temporal_coverage, auto_unbox = TRUE, digits = NA))
      self$`legal_notice` <- DatafileSimpleObject$`legal_notice`
      self$`weburl` <- DatafileSimpleObject$`weburl`
      self$`millesimes` <- ApiClient$new()$deserializeObj(DatafileSimpleObject$`millesimes`, "array[DatafileSimpleMillesimes]", loadNamespace("didoscalie"))
      self$`created_at` <- DatafileSimpleObject$`created_at`
      self$`last_modified` <- DatafileSimpleObject$`last_modified`
      self
    }
  )
)
