# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DatafileFullAllOf
#'
#' @description DatafileFullAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field dataset  \link{DatasetSimple} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DatafileFullAllOf <- R6::R6Class(
  'DatafileFullAllOf',
  public = list(
    `dataset` = NULL,
    initialize = function(
        `dataset`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`dataset`)) {
        stopifnot(R6::is.R6(`dataset`))
        self$`dataset` <- `dataset`
      }
    },
    toJSON = function() {
      DatafileFullAllOfObject <- list()
      if (!is.null(self$`dataset`)) {
        DatafileFullAllOfObject[['dataset']] <-
          self$`dataset`$toJSON()
      }

      DatafileFullAllOfObject
    },
    fromJSON = function(DatafileFullAllOfJson) {
      DatafileFullAllOfObject <- jsonlite::fromJSON(DatafileFullAllOfJson)
      if (!is.null(DatafileFullAllOfObject$`dataset`)) {
        datasetObject <- DatasetSimple$new()
        datasetObject$fromJSON(jsonlite::toJSON(DatafileFullAllOfObject$dataset, auto_unbox = TRUE, digits = NA))
        self$`dataset` <- datasetObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`dataset`)) {
        sprintf(
        '"dataset":
        %s
        ',
        jsonlite::toJSON(self$`dataset`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DatafileFullAllOfJson) {
      DatafileFullAllOfObject <- jsonlite::fromJSON(DatafileFullAllOfJson)
      self$`dataset` <- DatasetSimple$new()$fromJSON(jsonlite::toJSON(DatafileFullAllOfObject$dataset, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
