# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DatafileSimpleMillesimes
#'
#' @description DatafileSimpleMillesimes Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field millesime  character 
#'
#' @field date_diffusion  character 
#'
#' @field rows  integer [optional]
#'
#' @field columns  list( \link{DatafileSimpleColumns} ) [optional]
#'
#' @field extendedFilters  list( \link{DatafileSimpleExtendedFilters} ) [optional]
#'
#' @field geoFields  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DatafileSimpleMillesimes <- R6::R6Class(
  'DatafileSimpleMillesimes',
  public = list(
    `millesime` = NULL,
    `date_diffusion` = NULL,
    `rows` = NULL,
    `columns` = NULL,
    `extendedFilters` = NULL,
    `geoFields` = NULL,
    initialize = function(
        `millesime`, `date_diffusion`, `rows`=NULL, `columns`=NULL, `extendedFilters`=NULL, `geoFields`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`millesime`)) {
        stopifnot(is.character(`millesime`), length(`millesime`) == 1)
        self$`millesime` <- `millesime`
      }
      if (!missing(`date_diffusion`)) {
        stopifnot(is.character(`date_diffusion`), length(`date_diffusion`) == 1)
        self$`date_diffusion` <- `date_diffusion`
      }
      if (!is.null(`rows`)) {
        stopifnot(is.numeric(`rows`), length(`rows`) == 1)
        self$`rows` <- `rows`
      }
      if (!is.null(`columns`)) {
        stopifnot(is.vector(`columns`), length(`columns`) != 0)
        sapply(`columns`, function(x) stopifnot(R6::is.R6(x)))
        self$`columns` <- `columns`
      }
      if (!is.null(`extendedFilters`)) {
        stopifnot(is.vector(`extendedFilters`), length(`extendedFilters`) != 0)
        sapply(`extendedFilters`, function(x) stopifnot(R6::is.R6(x)))
        self$`extendedFilters` <- `extendedFilters`
      }
      if (!is.null(`geoFields`)) {
        stopifnot(is.vector(`geoFields`), length(`geoFields`) != 0)
        sapply(`geoFields`, function(x) stopifnot(is.character(x)))
        self$`geoFields` <- `geoFields`
      }
    },
    toJSON = function() {
      DatafileSimpleMillesimesObject <- list()
      if (!is.null(self$`millesime`)) {
        DatafileSimpleMillesimesObject[['millesime']] <-
          self$`millesime`
      }
      if (!is.null(self$`date_diffusion`)) {
        DatafileSimpleMillesimesObject[['date_diffusion']] <-
          self$`date_diffusion`
      }
      if (!is.null(self$`rows`)) {
        DatafileSimpleMillesimesObject[['rows']] <-
          self$`rows`
      }
      if (!is.null(self$`columns`)) {
        DatafileSimpleMillesimesObject[['columns']] <-
          lapply(self$`columns`, function(x) x$toJSON())
      }
      if (!is.null(self$`extendedFilters`)) {
        DatafileSimpleMillesimesObject[['extendedFilters']] <-
          lapply(self$`extendedFilters`, function(x) x$toJSON())
      }
      if (!is.null(self$`geoFields`)) {
        DatafileSimpleMillesimesObject[['geoFields']] <-
          self$`geoFields`
      }

      DatafileSimpleMillesimesObject
    },
    fromJSON = function(DatafileSimpleMillesimesJson) {
      DatafileSimpleMillesimesObject <- jsonlite::fromJSON(DatafileSimpleMillesimesJson)
      if (!is.null(DatafileSimpleMillesimesObject$`millesime`)) {
        self$`millesime` <- DatafileSimpleMillesimesObject$`millesime`
      }
      if (!is.null(DatafileSimpleMillesimesObject$`date_diffusion`)) {
        self$`date_diffusion` <- DatafileSimpleMillesimesObject$`date_diffusion`
      }
      if (!is.null(DatafileSimpleMillesimesObject$`rows`)) {
        self$`rows` <- DatafileSimpleMillesimesObject$`rows`
      }
      if (!is.null(DatafileSimpleMillesimesObject$`columns`)) {
        self$`columns` <- ApiClient$new()$deserializeObj(DatafileSimpleMillesimesObject$`columns`, "array[DatafileSimpleColumns]", loadNamespace("didoscalie"))
      }
      if (!is.null(DatafileSimpleMillesimesObject$`extendedFilters`)) {
        self$`extendedFilters` <- ApiClient$new()$deserializeObj(DatafileSimpleMillesimesObject$`extendedFilters`, "array[DatafileSimpleExtendedFilters]", loadNamespace("didoscalie"))
      }
      if (!is.null(DatafileSimpleMillesimesObject$`geoFields`)) {
        self$`geoFields` <- ApiClient$new()$deserializeObj(DatafileSimpleMillesimesObject$`geoFields`, "array[character]", loadNamespace("didoscalie"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`millesime`)) {
        sprintf(
        '"millesime":
          "%s"
                ',
        self$`millesime`
        )},
        if (!is.null(self$`date_diffusion`)) {
        sprintf(
        '"date_diffusion":
          "%s"
                ',
        self$`date_diffusion`
        )},
        if (!is.null(self$`rows`)) {
        sprintf(
        '"rows":
          %d
                ',
        self$`rows`
        )},
        if (!is.null(self$`columns`)) {
        sprintf(
        '"columns":
        [%s]
',
        paste(sapply(self$`columns`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`extendedFilters`)) {
        sprintf(
        '"extendedFilters":
        [%s]
',
        paste(sapply(self$`extendedFilters`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`geoFields`)) {
        sprintf(
        '"geoFields":
           [%s]
        ',
        paste(unlist(lapply(self$`geoFields`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DatafileSimpleMillesimesJson) {
      DatafileSimpleMillesimesObject <- jsonlite::fromJSON(DatafileSimpleMillesimesJson)
      self$`millesime` <- DatafileSimpleMillesimesObject$`millesime`
      self$`date_diffusion` <- DatafileSimpleMillesimesObject$`date_diffusion`
      self$`rows` <- DatafileSimpleMillesimesObject$`rows`
      self$`columns` <- ApiClient$new()$deserializeObj(DatafileSimpleMillesimesObject$`columns`, "array[DatafileSimpleColumns]", loadNamespace("didoscalie"))
      self$`extendedFilters` <- ApiClient$new()$deserializeObj(DatafileSimpleMillesimesObject$`extendedFilters`, "array[DatafileSimpleExtendedFilters]", loadNamespace("didoscalie"))
      self$`geoFields` <- ApiClient$new()$deserializeObj(DatafileSimpleMillesimesObject$`geoFields`, "array[character]", loadNamespace("didoscalie"))
      self
    }
  )
)
