# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DatafileSimpleTemporalCoverage
#'
#' @description DatafileSimpleTemporalCoverage Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field start  character 
#'
#' @field end  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DatafileSimpleTemporalCoverage <- R6::R6Class(
  'DatafileSimpleTemporalCoverage',
  public = list(
    `start` = NULL,
    `end` = NULL,
    initialize = function(
        `start`, `end`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`start`)) {
        stopifnot(is.character(`start`), length(`start`) == 1)
        self$`start` <- `start`
      }
      if (!missing(`end`)) {
        stopifnot(is.character(`end`), length(`end`) == 1)
        self$`end` <- `end`
      }
    },
    toJSON = function() {
      DatafileSimpleTemporalCoverageObject <- list()
      if (!is.null(self$`start`)) {
        DatafileSimpleTemporalCoverageObject[['start']] <-
          self$`start`
      }
      if (!is.null(self$`end`)) {
        DatafileSimpleTemporalCoverageObject[['end']] <-
          self$`end`
      }

      DatafileSimpleTemporalCoverageObject
    },
    fromJSON = function(DatafileSimpleTemporalCoverageJson) {
      DatafileSimpleTemporalCoverageObject <- jsonlite::fromJSON(DatafileSimpleTemporalCoverageJson)
      if (!is.null(DatafileSimpleTemporalCoverageObject$`start`)) {
        self$`start` <- DatafileSimpleTemporalCoverageObject$`start`
      }
      if (!is.null(DatafileSimpleTemporalCoverageObject$`end`)) {
        self$`end` <- DatafileSimpleTemporalCoverageObject$`end`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`start`)) {
        sprintf(
        '"start":
          "%s"
                ',
        self$`start`
        )},
        if (!is.null(self$`end`)) {
        sprintf(
        '"end":
          "%s"
                ',
        self$`end`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DatafileSimpleTemporalCoverageJson) {
      DatafileSimpleTemporalCoverageObject <- jsonlite::fromJSON(DatafileSimpleTemporalCoverageJson)
      self$`start` <- DatafileSimpleTemporalCoverageObject$`start`
      self$`end` <- DatafileSimpleTemporalCoverageObject$`end`
      self
    }
  )
)
