# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ItemPolluantsEau
#'
#' @description ItemPolluantsEau Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field CODE  character [optional]
#'
#' @field NAME  character [optional]
#'
#' @field UNIT  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ItemPolluantsEau <- R6::R6Class(
  'ItemPolluantsEau',
  public = list(
    `CODE` = NULL,
    `NAME` = NULL,
    `UNIT` = NULL,
    initialize = function(
        `CODE`=NULL, `NAME`=NULL, `UNIT`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`CODE`)) {
        stopifnot(is.character(`CODE`), length(`CODE`) == 1)
        self$`CODE` <- `CODE`
      }
      if (!is.null(`NAME`)) {
        stopifnot(is.character(`NAME`), length(`NAME`) == 1)
        self$`NAME` <- `NAME`
      }
      if (!is.null(`UNIT`)) {
        stopifnot(is.character(`UNIT`), length(`UNIT`) == 1)
        self$`UNIT` <- `UNIT`
      }
    },
    toJSON = function() {
      ItemPolluantsEauObject <- list()
      if (!is.null(self$`CODE`)) {
        ItemPolluantsEauObject[['CODE']] <-
          self$`CODE`
      }
      if (!is.null(self$`NAME`)) {
        ItemPolluantsEauObject[['NAME']] <-
          self$`NAME`
      }
      if (!is.null(self$`UNIT`)) {
        ItemPolluantsEauObject[['UNIT']] <-
          self$`UNIT`
      }

      ItemPolluantsEauObject
    },
    fromJSON = function(ItemPolluantsEauJson) {
      ItemPolluantsEauObject <- jsonlite::fromJSON(ItemPolluantsEauJson)
      if (!is.null(ItemPolluantsEauObject$`CODE`)) {
        self$`CODE` <- ItemPolluantsEauObject$`CODE`
      }
      if (!is.null(ItemPolluantsEauObject$`NAME`)) {
        self$`NAME` <- ItemPolluantsEauObject$`NAME`
      }
      if (!is.null(ItemPolluantsEauObject$`UNIT`)) {
        self$`UNIT` <- ItemPolluantsEauObject$`UNIT`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`CODE`)) {
        sprintf(
        '"CODE":
          "%s"
                ',
        self$`CODE`
        )},
        if (!is.null(self$`NAME`)) {
        sprintf(
        '"NAME":
          "%s"
                ',
        self$`NAME`
        )},
        if (!is.null(self$`UNIT`)) {
        sprintf(
        '"UNIT":
          "%s"
                ',
        self$`UNIT`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ItemPolluantsEauJson) {
      ItemPolluantsEauObject <- jsonlite::fromJSON(ItemPolluantsEauJson)
      self$`CODE` <- ItemPolluantsEauObject$`CODE`
      self$`NAME` <- ItemPolluantsEauObject$`NAME`
      self$`UNIT` <- ItemPolluantsEauObject$`UNIT`
      self
    }
  )
)
