# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ItemPorts
#'
#' @description ItemPorts Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field CODE  character [optional]
#'
#' @field NAME  character [optional]
#'
#' @field MCA_CODE  character [optional]
#'
#' @field MCA_NAME  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ItemPorts <- R6::R6Class(
  'ItemPorts',
  public = list(
    `CODE` = NULL,
    `NAME` = NULL,
    `MCA_CODE` = NULL,
    `MCA_NAME` = NULL,
    initialize = function(
        `CODE`=NULL, `NAME`=NULL, `MCA_CODE`=NULL, `MCA_NAME`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`CODE`)) {
        stopifnot(is.character(`CODE`), length(`CODE`) == 1)
        self$`CODE` <- `CODE`
      }
      if (!is.null(`NAME`)) {
        stopifnot(is.character(`NAME`), length(`NAME`) == 1)
        self$`NAME` <- `NAME`
      }
      if (!is.null(`MCA_CODE`)) {
        stopifnot(is.character(`MCA_CODE`), length(`MCA_CODE`) == 1)
        self$`MCA_CODE` <- `MCA_CODE`
      }
      if (!is.null(`MCA_NAME`)) {
        stopifnot(is.character(`MCA_NAME`), length(`MCA_NAME`) == 1)
        self$`MCA_NAME` <- `MCA_NAME`
      }
    },
    toJSON = function() {
      ItemPortsObject <- list()
      if (!is.null(self$`CODE`)) {
        ItemPortsObject[['CODE']] <-
          self$`CODE`
      }
      if (!is.null(self$`NAME`)) {
        ItemPortsObject[['NAME']] <-
          self$`NAME`
      }
      if (!is.null(self$`MCA_CODE`)) {
        ItemPortsObject[['MCA_CODE']] <-
          self$`MCA_CODE`
      }
      if (!is.null(self$`MCA_NAME`)) {
        ItemPortsObject[['MCA_NAME']] <-
          self$`MCA_NAME`
      }

      ItemPortsObject
    },
    fromJSON = function(ItemPortsJson) {
      ItemPortsObject <- jsonlite::fromJSON(ItemPortsJson)
      if (!is.null(ItemPortsObject$`CODE`)) {
        self$`CODE` <- ItemPortsObject$`CODE`
      }
      if (!is.null(ItemPortsObject$`NAME`)) {
        self$`NAME` <- ItemPortsObject$`NAME`
      }
      if (!is.null(ItemPortsObject$`MCA_CODE`)) {
        self$`MCA_CODE` <- ItemPortsObject$`MCA_CODE`
      }
      if (!is.null(ItemPortsObject$`MCA_NAME`)) {
        self$`MCA_NAME` <- ItemPortsObject$`MCA_NAME`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`CODE`)) {
        sprintf(
        '"CODE":
          "%s"
                ',
        self$`CODE`
        )},
        if (!is.null(self$`NAME`)) {
        sprintf(
        '"NAME":
          "%s"
                ',
        self$`NAME`
        )},
        if (!is.null(self$`MCA_CODE`)) {
        sprintf(
        '"MCA_CODE":
          "%s"
                ',
        self$`MCA_CODE`
        )},
        if (!is.null(self$`MCA_NAME`)) {
        sprintf(
        '"MCA_NAME":
          "%s"
                ',
        self$`MCA_NAME`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ItemPortsJson) {
      ItemPortsObject <- jsonlite::fromJSON(ItemPortsJson)
      self$`CODE` <- ItemPortsObject$`CODE`
      self$`NAME` <- ItemPortsObject$`NAME`
      self$`MCA_CODE` <- ItemPortsObject$`MCA_CODE`
      self$`MCA_NAME` <- ItemPortsObject$`MCA_NAME`
      self
    }
  )
)
