# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ItemTags
#'
#' @description ItemTags Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field VALUE  character [optional]
#'
#' @field DISPLAY  character [optional]
#'
#' @field TOPICS  character [optional]
#'
#' @field EUROVOC  character [optional]
#'
#' @field ECOPLANET  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ItemTags <- R6::R6Class(
  'ItemTags',
  public = list(
    `VALUE` = NULL,
    `DISPLAY` = NULL,
    `TOPICS` = NULL,
    `EUROVOC` = NULL,
    `ECOPLANET` = NULL,
    initialize = function(
        `VALUE`=NULL, `DISPLAY`=NULL, `TOPICS`=NULL, `EUROVOC`=NULL, `ECOPLANET`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`VALUE`)) {
        stopifnot(is.character(`VALUE`), length(`VALUE`) == 1)
        self$`VALUE` <- `VALUE`
      }
      if (!is.null(`DISPLAY`)) {
        stopifnot(is.character(`DISPLAY`), length(`DISPLAY`) == 1)
        self$`DISPLAY` <- `DISPLAY`
      }
      if (!is.null(`TOPICS`)) {
        stopifnot(is.character(`TOPICS`), length(`TOPICS`) == 1)
        self$`TOPICS` <- `TOPICS`
      }
      if (!is.null(`EUROVOC`)) {
        stopifnot(is.character(`EUROVOC`), length(`EUROVOC`) == 1)
        self$`EUROVOC` <- `EUROVOC`
      }
      if (!is.null(`ECOPLANET`)) {
        stopifnot(is.character(`ECOPLANET`), length(`ECOPLANET`) == 1)
        self$`ECOPLANET` <- `ECOPLANET`
      }
    },
    toJSON = function() {
      ItemTagsObject <- list()
      if (!is.null(self$`VALUE`)) {
        ItemTagsObject[['VALUE']] <-
          self$`VALUE`
      }
      if (!is.null(self$`DISPLAY`)) {
        ItemTagsObject[['DISPLAY']] <-
          self$`DISPLAY`
      }
      if (!is.null(self$`TOPICS`)) {
        ItemTagsObject[['TOPICS']] <-
          self$`TOPICS`
      }
      if (!is.null(self$`EUROVOC`)) {
        ItemTagsObject[['EUROVOC']] <-
          self$`EUROVOC`
      }
      if (!is.null(self$`ECOPLANET`)) {
        ItemTagsObject[['ECOPLANET']] <-
          self$`ECOPLANET`
      }

      ItemTagsObject
    },
    fromJSON = function(ItemTagsJson) {
      ItemTagsObject <- jsonlite::fromJSON(ItemTagsJson)
      if (!is.null(ItemTagsObject$`VALUE`)) {
        self$`VALUE` <- ItemTagsObject$`VALUE`
      }
      if (!is.null(ItemTagsObject$`DISPLAY`)) {
        self$`DISPLAY` <- ItemTagsObject$`DISPLAY`
      }
      if (!is.null(ItemTagsObject$`TOPICS`)) {
        self$`TOPICS` <- ItemTagsObject$`TOPICS`
      }
      if (!is.null(ItemTagsObject$`EUROVOC`)) {
        self$`EUROVOC` <- ItemTagsObject$`EUROVOC`
      }
      if (!is.null(ItemTagsObject$`ECOPLANET`)) {
        self$`ECOPLANET` <- ItemTagsObject$`ECOPLANET`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`VALUE`)) {
        sprintf(
        '"VALUE":
          "%s"
                ',
        self$`VALUE`
        )},
        if (!is.null(self$`DISPLAY`)) {
        sprintf(
        '"DISPLAY":
          "%s"
                ',
        self$`DISPLAY`
        )},
        if (!is.null(self$`TOPICS`)) {
        sprintf(
        '"TOPICS":
          "%s"
                ',
        self$`TOPICS`
        )},
        if (!is.null(self$`EUROVOC`)) {
        sprintf(
        '"EUROVOC":
          "%s"
                ',
        self$`EUROVOC`
        )},
        if (!is.null(self$`ECOPLANET`)) {
        sprintf(
        '"ECOPLANET":
          "%s"
                ',
        self$`ECOPLANET`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ItemTagsJson) {
      ItemTagsObject <- jsonlite::fromJSON(ItemTagsJson)
      self$`VALUE` <- ItemTagsObject$`VALUE`
      self$`DISPLAY` <- ItemTagsObject$`DISPLAY`
      self$`TOPICS` <- ItemTagsObject$`TOPICS`
      self$`EUROVOC` <- ItemTagsObject$`EUROVOC`
      self$`ECOPLANET` <- ItemTagsObject$`ECOPLANET`
      self
    }
  )
)
