# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ItemCog
#'
#' @description ItemCog Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field ID  character [optional]
#'
#' @field MILLESIME  integer [optional]
#'
#' @field TYPE  character [optional]
#'
#' @field LEVEL  character [optional]
#'
#' @field CODE_MILLESIME  character [optional]
#'
#' @field CODE_CURRENT  character [optional]
#'
#' @field OFFICIAL_NAME  character [optional]
#'
#' @field UPPER_NAME  character [optional]
#'
#' @field LOWER_NAME  character [optional]
#'
#' @field LONGITUDE  numeric [optional]
#'
#' @field LATITUDE  numeric [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ItemCog <- R6::R6Class(
  'ItemCog',
  public = list(
    `ID` = NULL,
    `MILLESIME` = NULL,
    `TYPE` = NULL,
    `LEVEL` = NULL,
    `CODE_MILLESIME` = NULL,
    `CODE_CURRENT` = NULL,
    `OFFICIAL_NAME` = NULL,
    `UPPER_NAME` = NULL,
    `LOWER_NAME` = NULL,
    `LONGITUDE` = NULL,
    `LATITUDE` = NULL,
    initialize = function(
        `ID`=NULL, `MILLESIME`=NULL, `TYPE`=NULL, `LEVEL`=NULL, `CODE_MILLESIME`=NULL, `CODE_CURRENT`=NULL, `OFFICIAL_NAME`=NULL, `UPPER_NAME`=NULL, `LOWER_NAME`=NULL, `LONGITUDE`=NULL, `LATITUDE`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`ID`)) {
        stopifnot(is.character(`ID`), length(`ID`) == 1)
        self$`ID` <- `ID`
      }
      if (!is.null(`MILLESIME`)) {
        stopifnot(is.numeric(`MILLESIME`), length(`MILLESIME`) == 1)
        self$`MILLESIME` <- `MILLESIME`
      }
      if (!is.null(`TYPE`)) {
        stopifnot(is.character(`TYPE`), length(`TYPE`) == 1)
        self$`TYPE` <- `TYPE`
      }
      if (!is.null(`LEVEL`)) {
        stopifnot(is.character(`LEVEL`), length(`LEVEL`) == 1)
        self$`LEVEL` <- `LEVEL`
      }
      if (!is.null(`CODE_MILLESIME`)) {
        stopifnot(is.character(`CODE_MILLESIME`), length(`CODE_MILLESIME`) == 1)
        self$`CODE_MILLESIME` <- `CODE_MILLESIME`
      }
      if (!is.null(`CODE_CURRENT`)) {
        stopifnot(is.character(`CODE_CURRENT`), length(`CODE_CURRENT`) == 1)
        self$`CODE_CURRENT` <- `CODE_CURRENT`
      }
      if (!is.null(`OFFICIAL_NAME`)) {
        stopifnot(is.character(`OFFICIAL_NAME`), length(`OFFICIAL_NAME`) == 1)
        self$`OFFICIAL_NAME` <- `OFFICIAL_NAME`
      }
      if (!is.null(`UPPER_NAME`)) {
        stopifnot(is.character(`UPPER_NAME`), length(`UPPER_NAME`) == 1)
        self$`UPPER_NAME` <- `UPPER_NAME`
      }
      if (!is.null(`LOWER_NAME`)) {
        stopifnot(is.character(`LOWER_NAME`), length(`LOWER_NAME`) == 1)
        self$`LOWER_NAME` <- `LOWER_NAME`
      }
      if (!is.null(`LONGITUDE`)) {
        self$`LONGITUDE` <- `LONGITUDE`
      }
      if (!is.null(`LATITUDE`)) {
        self$`LATITUDE` <- `LATITUDE`
      }
    },
    toJSON = function() {
      ItemCogObject <- list()
      if (!is.null(self$`ID`)) {
        ItemCogObject[['ID']] <-
          self$`ID`
      }
      if (!is.null(self$`MILLESIME`)) {
        ItemCogObject[['MILLESIME']] <-
          self$`MILLESIME`
      }
      if (!is.null(self$`TYPE`)) {
        ItemCogObject[['TYPE']] <-
          self$`TYPE`
      }
      if (!is.null(self$`LEVEL`)) {
        ItemCogObject[['LEVEL']] <-
          self$`LEVEL`
      }
      if (!is.null(self$`CODE_MILLESIME`)) {
        ItemCogObject[['CODE_MILLESIME']] <-
          self$`CODE_MILLESIME`
      }
      if (!is.null(self$`CODE_CURRENT`)) {
        ItemCogObject[['CODE_CURRENT']] <-
          self$`CODE_CURRENT`
      }
      if (!is.null(self$`OFFICIAL_NAME`)) {
        ItemCogObject[['OFFICIAL_NAME']] <-
          self$`OFFICIAL_NAME`
      }
      if (!is.null(self$`UPPER_NAME`)) {
        ItemCogObject[['UPPER_NAME']] <-
          self$`UPPER_NAME`
      }
      if (!is.null(self$`LOWER_NAME`)) {
        ItemCogObject[['LOWER_NAME']] <-
          self$`LOWER_NAME`
      }
      if (!is.null(self$`LONGITUDE`)) {
        ItemCogObject[['LONGITUDE']] <-
          self$`LONGITUDE`
      }
      if (!is.null(self$`LATITUDE`)) {
        ItemCogObject[['LATITUDE']] <-
          self$`LATITUDE`
      }

      ItemCogObject
    },
    fromJSON = function(ItemCogJson) {
      ItemCogObject <- jsonlite::fromJSON(ItemCogJson)
      if (!is.null(ItemCogObject$`ID`)) {
        self$`ID` <- ItemCogObject$`ID`
      }
      if (!is.null(ItemCogObject$`MILLESIME`)) {
        self$`MILLESIME` <- ItemCogObject$`MILLESIME`
      }
      if (!is.null(ItemCogObject$`TYPE`)) {
        self$`TYPE` <- ItemCogObject$`TYPE`
      }
      if (!is.null(ItemCogObject$`LEVEL`)) {
        self$`LEVEL` <- ItemCogObject$`LEVEL`
      }
      if (!is.null(ItemCogObject$`CODE_MILLESIME`)) {
        self$`CODE_MILLESIME` <- ItemCogObject$`CODE_MILLESIME`
      }
      if (!is.null(ItemCogObject$`CODE_CURRENT`)) {
        self$`CODE_CURRENT` <- ItemCogObject$`CODE_CURRENT`
      }
      if (!is.null(ItemCogObject$`OFFICIAL_NAME`)) {
        self$`OFFICIAL_NAME` <- ItemCogObject$`OFFICIAL_NAME`
      }
      if (!is.null(ItemCogObject$`UPPER_NAME`)) {
        self$`UPPER_NAME` <- ItemCogObject$`UPPER_NAME`
      }
      if (!is.null(ItemCogObject$`LOWER_NAME`)) {
        self$`LOWER_NAME` <- ItemCogObject$`LOWER_NAME`
      }
      if (!is.null(ItemCogObject$`LONGITUDE`)) {
        self$`LONGITUDE` <- ItemCogObject$`LONGITUDE`
      }
      if (!is.null(ItemCogObject$`LATITUDE`)) {
        self$`LATITUDE` <- ItemCogObject$`LATITUDE`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`ID`)) {
        sprintf(
        '"ID":
          "%s"
                ',
        self$`ID`
        )},
        if (!is.null(self$`MILLESIME`)) {
        sprintf(
        '"MILLESIME":
          %d
                ',
        self$`MILLESIME`
        )},
        if (!is.null(self$`TYPE`)) {
        sprintf(
        '"TYPE":
          "%s"
                ',
        self$`TYPE`
        )},
        if (!is.null(self$`LEVEL`)) {
        sprintf(
        '"LEVEL":
          "%s"
                ',
        self$`LEVEL`
        )},
        if (!is.null(self$`CODE_MILLESIME`)) {
        sprintf(
        '"CODE_MILLESIME":
          "%s"
                ',
        self$`CODE_MILLESIME`
        )},
        if (!is.null(self$`CODE_CURRENT`)) {
        sprintf(
        '"CODE_CURRENT":
          "%s"
                ',
        self$`CODE_CURRENT`
        )},
        if (!is.null(self$`OFFICIAL_NAME`)) {
        sprintf(
        '"OFFICIAL_NAME":
          "%s"
                ',
        self$`OFFICIAL_NAME`
        )},
        if (!is.null(self$`UPPER_NAME`)) {
        sprintf(
        '"UPPER_NAME":
          "%s"
                ',
        self$`UPPER_NAME`
        )},
        if (!is.null(self$`LOWER_NAME`)) {
        sprintf(
        '"LOWER_NAME":
          "%s"
                ',
        self$`LOWER_NAME`
        )},
        if (!is.null(self$`LONGITUDE`)) {
        sprintf(
        '"LONGITUDE":
          %d
                ',
        self$`LONGITUDE`
        )},
        if (!is.null(self$`LATITUDE`)) {
        sprintf(
        '"LATITUDE":
          %d
                ',
        self$`LATITUDE`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ItemCogJson) {
      ItemCogObject <- jsonlite::fromJSON(ItemCogJson)
      self$`ID` <- ItemCogObject$`ID`
      self$`MILLESIME` <- ItemCogObject$`MILLESIME`
      self$`TYPE` <- ItemCogObject$`TYPE`
      self$`LEVEL` <- ItemCogObject$`LEVEL`
      self$`CODE_MILLESIME` <- ItemCogObject$`CODE_MILLESIME`
      self$`CODE_CURRENT` <- ItemCogObject$`CODE_CURRENT`
      self$`OFFICIAL_NAME` <- ItemCogObject$`OFFICIAL_NAME`
      self$`UPPER_NAME` <- ItemCogObject$`UPPER_NAME`
      self$`LOWER_NAME` <- ItemCogObject$`LOWER_NAME`
      self$`LONGITUDE` <- ItemCogObject$`LONGITUDE`
      self$`LATITUDE` <- ItemCogObject$`LATITUDE`
      self
    }
  )
)
