# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ItemGeozones
#'
#' @description ItemGeozones Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field ID  character [optional]
#'
#' @field LEVEL  character [optional]
#'
#' @field CODE  character [optional]
#'
#' @field VALIDITY_START  character [optional]
#'
#' @field VALIDITY_END  character [optional]
#'
#' @field NAME  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ItemGeozones <- R6::R6Class(
  'ItemGeozones',
  public = list(
    `ID` = NULL,
    `LEVEL` = NULL,
    `CODE` = NULL,
    `VALIDITY_START` = NULL,
    `VALIDITY_END` = NULL,
    `NAME` = NULL,
    initialize = function(
        `ID`=NULL, `LEVEL`=NULL, `CODE`=NULL, `VALIDITY_START`=NULL, `VALIDITY_END`=NULL, `NAME`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`ID`)) {
        stopifnot(is.character(`ID`), length(`ID`) == 1)
        self$`ID` <- `ID`
      }
      if (!is.null(`LEVEL`)) {
        stopifnot(is.character(`LEVEL`), length(`LEVEL`) == 1)
        self$`LEVEL` <- `LEVEL`
      }
      if (!is.null(`CODE`)) {
        stopifnot(is.character(`CODE`), length(`CODE`) == 1)
        self$`CODE` <- `CODE`
      }
      if (!is.null(`VALIDITY_START`)) {
        stopifnot(is.character(`VALIDITY_START`), length(`VALIDITY_START`) == 1)
        self$`VALIDITY_START` <- `VALIDITY_START`
      }
      if (!is.null(`VALIDITY_END`)) {
        stopifnot(is.character(`VALIDITY_END`), length(`VALIDITY_END`) == 1)
        self$`VALIDITY_END` <- `VALIDITY_END`
      }
      if (!is.null(`NAME`)) {
        stopifnot(is.character(`NAME`), length(`NAME`) == 1)
        self$`NAME` <- `NAME`
      }
    },
    toJSON = function() {
      ItemGeozonesObject <- list()
      if (!is.null(self$`ID`)) {
        ItemGeozonesObject[['ID']] <-
          self$`ID`
      }
      if (!is.null(self$`LEVEL`)) {
        ItemGeozonesObject[['LEVEL']] <-
          self$`LEVEL`
      }
      if (!is.null(self$`CODE`)) {
        ItemGeozonesObject[['CODE']] <-
          self$`CODE`
      }
      if (!is.null(self$`VALIDITY_START`)) {
        ItemGeozonesObject[['VALIDITY_START']] <-
          self$`VALIDITY_START`
      }
      if (!is.null(self$`VALIDITY_END`)) {
        ItemGeozonesObject[['VALIDITY_END']] <-
          self$`VALIDITY_END`
      }
      if (!is.null(self$`NAME`)) {
        ItemGeozonesObject[['NAME']] <-
          self$`NAME`
      }

      ItemGeozonesObject
    },
    fromJSON = function(ItemGeozonesJson) {
      ItemGeozonesObject <- jsonlite::fromJSON(ItemGeozonesJson)
      if (!is.null(ItemGeozonesObject$`ID`)) {
        self$`ID` <- ItemGeozonesObject$`ID`
      }
      if (!is.null(ItemGeozonesObject$`LEVEL`)) {
        self$`LEVEL` <- ItemGeozonesObject$`LEVEL`
      }
      if (!is.null(ItemGeozonesObject$`CODE`)) {
        self$`CODE` <- ItemGeozonesObject$`CODE`
      }
      if (!is.null(ItemGeozonesObject$`VALIDITY_START`)) {
        self$`VALIDITY_START` <- ItemGeozonesObject$`VALIDITY_START`
      }
      if (!is.null(ItemGeozonesObject$`VALIDITY_END`)) {
        self$`VALIDITY_END` <- ItemGeozonesObject$`VALIDITY_END`
      }
      if (!is.null(ItemGeozonesObject$`NAME`)) {
        self$`NAME` <- ItemGeozonesObject$`NAME`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`ID`)) {
        sprintf(
        '"ID":
          "%s"
                ',
        self$`ID`
        )},
        if (!is.null(self$`LEVEL`)) {
        sprintf(
        '"LEVEL":
          "%s"
                ',
        self$`LEVEL`
        )},
        if (!is.null(self$`CODE`)) {
        sprintf(
        '"CODE":
          "%s"
                ',
        self$`CODE`
        )},
        if (!is.null(self$`VALIDITY_START`)) {
        sprintf(
        '"VALIDITY_START":
          "%s"
                ',
        self$`VALIDITY_START`
        )},
        if (!is.null(self$`VALIDITY_END`)) {
        sprintf(
        '"VALIDITY_END":
          "%s"
                ',
        self$`VALIDITY_END`
        )},
        if (!is.null(self$`NAME`)) {
        sprintf(
        '"NAME":
          "%s"
                ',
        self$`NAME`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ItemGeozonesJson) {
      ItemGeozonesObject <- jsonlite::fromJSON(ItemGeozonesJson)
      self$`ID` <- ItemGeozonesObject$`ID`
      self$`LEVEL` <- ItemGeozonesObject$`LEVEL`
      self$`CODE` <- ItemGeozonesObject$`CODE`
      self$`VALIDITY_START` <- ItemGeozonesObject$`VALIDITY_START`
      self$`VALIDITY_END` <- ItemGeozonesObject$`VALIDITY_END`
      self$`NAME` <- ItemGeozonesObject$`NAME`
      self
    }
  )
)
