# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ItemCslOperations
#'
#' @description ItemCslOperations Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field CODE_1  character [optional]
#'
#' @field NAME_1  character [optional]
#'
#' @field CODE_2  character [optional]
#'
#' @field NAME_2  character [optional]
#'
#' @field CODE_3  character [optional]
#'
#' @field NAME_3  character [optional]
#'
#' @field CODE_4  character [optional]
#'
#' @field NAME_4  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ItemCslOperations <- R6::R6Class(
  'ItemCslOperations',
  public = list(
    `CODE_1` = NULL,
    `NAME_1` = NULL,
    `CODE_2` = NULL,
    `NAME_2` = NULL,
    `CODE_3` = NULL,
    `NAME_3` = NULL,
    `CODE_4` = NULL,
    `NAME_4` = NULL,
    initialize = function(
        `CODE_1`=NULL, `NAME_1`=NULL, `CODE_2`=NULL, `NAME_2`=NULL, `CODE_3`=NULL, `NAME_3`=NULL, `CODE_4`=NULL, `NAME_4`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`CODE_1`)) {
        stopifnot(is.character(`CODE_1`), length(`CODE_1`) == 1)
        self$`CODE_1` <- `CODE_1`
      }
      if (!is.null(`NAME_1`)) {
        stopifnot(is.character(`NAME_1`), length(`NAME_1`) == 1)
        self$`NAME_1` <- `NAME_1`
      }
      if (!is.null(`CODE_2`)) {
        stopifnot(is.character(`CODE_2`), length(`CODE_2`) == 1)
        self$`CODE_2` <- `CODE_2`
      }
      if (!is.null(`NAME_2`)) {
        stopifnot(is.character(`NAME_2`), length(`NAME_2`) == 1)
        self$`NAME_2` <- `NAME_2`
      }
      if (!is.null(`CODE_3`)) {
        stopifnot(is.character(`CODE_3`), length(`CODE_3`) == 1)
        self$`CODE_3` <- `CODE_3`
      }
      if (!is.null(`NAME_3`)) {
        stopifnot(is.character(`NAME_3`), length(`NAME_3`) == 1)
        self$`NAME_3` <- `NAME_3`
      }
      if (!is.null(`CODE_4`)) {
        stopifnot(is.character(`CODE_4`), length(`CODE_4`) == 1)
        self$`CODE_4` <- `CODE_4`
      }
      if (!is.null(`NAME_4`)) {
        stopifnot(is.character(`NAME_4`), length(`NAME_4`) == 1)
        self$`NAME_4` <- `NAME_4`
      }
    },
    toJSON = function() {
      ItemCslOperationsObject <- list()
      if (!is.null(self$`CODE_1`)) {
        ItemCslOperationsObject[['CODE_1']] <-
          self$`CODE_1`
      }
      if (!is.null(self$`NAME_1`)) {
        ItemCslOperationsObject[['NAME_1']] <-
          self$`NAME_1`
      }
      if (!is.null(self$`CODE_2`)) {
        ItemCslOperationsObject[['CODE_2']] <-
          self$`CODE_2`
      }
      if (!is.null(self$`NAME_2`)) {
        ItemCslOperationsObject[['NAME_2']] <-
          self$`NAME_2`
      }
      if (!is.null(self$`CODE_3`)) {
        ItemCslOperationsObject[['CODE_3']] <-
          self$`CODE_3`
      }
      if (!is.null(self$`NAME_3`)) {
        ItemCslOperationsObject[['NAME_3']] <-
          self$`NAME_3`
      }
      if (!is.null(self$`CODE_4`)) {
        ItemCslOperationsObject[['CODE_4']] <-
          self$`CODE_4`
      }
      if (!is.null(self$`NAME_4`)) {
        ItemCslOperationsObject[['NAME_4']] <-
          self$`NAME_4`
      }

      ItemCslOperationsObject
    },
    fromJSON = function(ItemCslOperationsJson) {
      ItemCslOperationsObject <- jsonlite::fromJSON(ItemCslOperationsJson)
      if (!is.null(ItemCslOperationsObject$`CODE_1`)) {
        self$`CODE_1` <- ItemCslOperationsObject$`CODE_1`
      }
      if (!is.null(ItemCslOperationsObject$`NAME_1`)) {
        self$`NAME_1` <- ItemCslOperationsObject$`NAME_1`
      }
      if (!is.null(ItemCslOperationsObject$`CODE_2`)) {
        self$`CODE_2` <- ItemCslOperationsObject$`CODE_2`
      }
      if (!is.null(ItemCslOperationsObject$`NAME_2`)) {
        self$`NAME_2` <- ItemCslOperationsObject$`NAME_2`
      }
      if (!is.null(ItemCslOperationsObject$`CODE_3`)) {
        self$`CODE_3` <- ItemCslOperationsObject$`CODE_3`
      }
      if (!is.null(ItemCslOperationsObject$`NAME_3`)) {
        self$`NAME_3` <- ItemCslOperationsObject$`NAME_3`
      }
      if (!is.null(ItemCslOperationsObject$`CODE_4`)) {
        self$`CODE_4` <- ItemCslOperationsObject$`CODE_4`
      }
      if (!is.null(ItemCslOperationsObject$`NAME_4`)) {
        self$`NAME_4` <- ItemCslOperationsObject$`NAME_4`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`CODE_1`)) {
        sprintf(
        '"CODE_1":
          "%s"
                ',
        self$`CODE_1`
        )},
        if (!is.null(self$`NAME_1`)) {
        sprintf(
        '"NAME_1":
          "%s"
                ',
        self$`NAME_1`
        )},
        if (!is.null(self$`CODE_2`)) {
        sprintf(
        '"CODE_2":
          "%s"
                ',
        self$`CODE_2`
        )},
        if (!is.null(self$`NAME_2`)) {
        sprintf(
        '"NAME_2":
          "%s"
                ',
        self$`NAME_2`
        )},
        if (!is.null(self$`CODE_3`)) {
        sprintf(
        '"CODE_3":
          "%s"
                ',
        self$`CODE_3`
        )},
        if (!is.null(self$`NAME_3`)) {
        sprintf(
        '"NAME_3":
          "%s"
                ',
        self$`NAME_3`
        )},
        if (!is.null(self$`CODE_4`)) {
        sprintf(
        '"CODE_4":
          "%s"
                ',
        self$`CODE_4`
        )},
        if (!is.null(self$`NAME_4`)) {
        sprintf(
        '"NAME_4":
          "%s"
                ',
        self$`NAME_4`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ItemCslOperationsJson) {
      ItemCslOperationsObject <- jsonlite::fromJSON(ItemCslOperationsJson)
      self$`CODE_1` <- ItemCslOperationsObject$`CODE_1`
      self$`NAME_1` <- ItemCslOperationsObject$`NAME_1`
      self$`CODE_2` <- ItemCslOperationsObject$`CODE_2`
      self$`NAME_2` <- ItemCslOperationsObject$`NAME_2`
      self$`CODE_3` <- ItemCslOperationsObject$`CODE_3`
      self$`NAME_3` <- ItemCslOperationsObject$`NAME_3`
      self$`CODE_4` <- ItemCslOperationsObject$`CODE_4`
      self$`NAME_4` <- ItemCslOperationsObject$`NAME_4`
      self
    }
  )
)
