# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ItemCslFilieres
#'
#' @description ItemCslFilieres Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field CODE  character [optional]
#'
#' @field NAME  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ItemCslFilieres <- R6::R6Class(
  'ItemCslFilieres',
  public = list(
    `CODE` = NULL,
    `NAME` = NULL,
    initialize = function(
        `CODE`=NULL, `NAME`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`CODE`)) {
        stopifnot(is.character(`CODE`), length(`CODE`) == 1)
        self$`CODE` <- `CODE`
      }
      if (!is.null(`NAME`)) {
        stopifnot(is.character(`NAME`), length(`NAME`) == 1)
        self$`NAME` <- `NAME`
      }
    },
    toJSON = function() {
      ItemCslFilieresObject <- list()
      if (!is.null(self$`CODE`)) {
        ItemCslFilieresObject[['CODE']] <-
          self$`CODE`
      }
      if (!is.null(self$`NAME`)) {
        ItemCslFilieresObject[['NAME']] <-
          self$`NAME`
      }

      ItemCslFilieresObject
    },
    fromJSON = function(ItemCslFilieresJson) {
      ItemCslFilieresObject <- jsonlite::fromJSON(ItemCslFilieresJson)
      if (!is.null(ItemCslFilieresObject$`CODE`)) {
        self$`CODE` <- ItemCslFilieresObject$`CODE`
      }
      if (!is.null(ItemCslFilieresObject$`NAME`)) {
        self$`NAME` <- ItemCslFilieresObject$`NAME`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`CODE`)) {
        sprintf(
        '"CODE":
          "%s"
                ',
        self$`CODE`
        )},
        if (!is.null(self$`NAME`)) {
        sprintf(
        '"NAME":
          "%s"
                ',
        self$`NAME`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ItemCslFilieresJson) {
      ItemCslFilieresObject <- jsonlite::fromJSON(ItemCslFilieresJson)
      self$`CODE` <- ItemCslFilieresObject$`CODE`
      self$`NAME` <- ItemCslFilieresObject$`NAME`
      self
    }
  )
)
