# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ItemBilanEnergie
#'
#' @description ItemBilanEnergie Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field CODE  character [optional]
#'
#' @field NAME  character [optional]
#'
#' @field UNIT  character [optional]
#'
#' @field LEVEL  character [optional]
#'
#' @field DATA_TYPE  character [optional]
#'
#' @field FLOW_TYPE  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ItemBilanEnergie <- R6::R6Class(
  'ItemBilanEnergie',
  public = list(
    `CODE` = NULL,
    `NAME` = NULL,
    `UNIT` = NULL,
    `LEVEL` = NULL,
    `DATA_TYPE` = NULL,
    `FLOW_TYPE` = NULL,
    initialize = function(
        `CODE`=NULL, `NAME`=NULL, `UNIT`=NULL, `LEVEL`=NULL, `DATA_TYPE`=NULL, `FLOW_TYPE`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`CODE`)) {
        stopifnot(is.character(`CODE`), length(`CODE`) == 1)
        self$`CODE` <- `CODE`
      }
      if (!is.null(`NAME`)) {
        stopifnot(is.character(`NAME`), length(`NAME`) == 1)
        self$`NAME` <- `NAME`
      }
      if (!is.null(`UNIT`)) {
        stopifnot(is.character(`UNIT`), length(`UNIT`) == 1)
        self$`UNIT` <- `UNIT`
      }
      if (!is.null(`LEVEL`)) {
        stopifnot(is.character(`LEVEL`), length(`LEVEL`) == 1)
        self$`LEVEL` <- `LEVEL`
      }
      if (!is.null(`DATA_TYPE`)) {
        stopifnot(is.character(`DATA_TYPE`), length(`DATA_TYPE`) == 1)
        self$`DATA_TYPE` <- `DATA_TYPE`
      }
      if (!is.null(`FLOW_TYPE`)) {
        stopifnot(is.character(`FLOW_TYPE`), length(`FLOW_TYPE`) == 1)
        self$`FLOW_TYPE` <- `FLOW_TYPE`
      }
    },
    toJSON = function() {
      ItemBilanEnergieObject <- list()
      if (!is.null(self$`CODE`)) {
        ItemBilanEnergieObject[['CODE']] <-
          self$`CODE`
      }
      if (!is.null(self$`NAME`)) {
        ItemBilanEnergieObject[['NAME']] <-
          self$`NAME`
      }
      if (!is.null(self$`UNIT`)) {
        ItemBilanEnergieObject[['UNIT']] <-
          self$`UNIT`
      }
      if (!is.null(self$`LEVEL`)) {
        ItemBilanEnergieObject[['LEVEL']] <-
          self$`LEVEL`
      }
      if (!is.null(self$`DATA_TYPE`)) {
        ItemBilanEnergieObject[['DATA_TYPE']] <-
          self$`DATA_TYPE`
      }
      if (!is.null(self$`FLOW_TYPE`)) {
        ItemBilanEnergieObject[['FLOW_TYPE']] <-
          self$`FLOW_TYPE`
      }

      ItemBilanEnergieObject
    },
    fromJSON = function(ItemBilanEnergieJson) {
      ItemBilanEnergieObject <- jsonlite::fromJSON(ItemBilanEnergieJson)
      if (!is.null(ItemBilanEnergieObject$`CODE`)) {
        self$`CODE` <- ItemBilanEnergieObject$`CODE`
      }
      if (!is.null(ItemBilanEnergieObject$`NAME`)) {
        self$`NAME` <- ItemBilanEnergieObject$`NAME`
      }
      if (!is.null(ItemBilanEnergieObject$`UNIT`)) {
        self$`UNIT` <- ItemBilanEnergieObject$`UNIT`
      }
      if (!is.null(ItemBilanEnergieObject$`LEVEL`)) {
        self$`LEVEL` <- ItemBilanEnergieObject$`LEVEL`
      }
      if (!is.null(ItemBilanEnergieObject$`DATA_TYPE`)) {
        self$`DATA_TYPE` <- ItemBilanEnergieObject$`DATA_TYPE`
      }
      if (!is.null(ItemBilanEnergieObject$`FLOW_TYPE`)) {
        self$`FLOW_TYPE` <- ItemBilanEnergieObject$`FLOW_TYPE`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`CODE`)) {
        sprintf(
        '"CODE":
          "%s"
                ',
        self$`CODE`
        )},
        if (!is.null(self$`NAME`)) {
        sprintf(
        '"NAME":
          "%s"
                ',
        self$`NAME`
        )},
        if (!is.null(self$`UNIT`)) {
        sprintf(
        '"UNIT":
          "%s"
                ',
        self$`UNIT`
        )},
        if (!is.null(self$`LEVEL`)) {
        sprintf(
        '"LEVEL":
          "%s"
                ',
        self$`LEVEL`
        )},
        if (!is.null(self$`DATA_TYPE`)) {
        sprintf(
        '"DATA_TYPE":
          "%s"
                ',
        self$`DATA_TYPE`
        )},
        if (!is.null(self$`FLOW_TYPE`)) {
        sprintf(
        '"FLOW_TYPE":
          "%s"
                ',
        self$`FLOW_TYPE`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ItemBilanEnergieJson) {
      ItemBilanEnergieObject <- jsonlite::fromJSON(ItemBilanEnergieJson)
      self$`CODE` <- ItemBilanEnergieObject$`CODE`
      self$`NAME` <- ItemBilanEnergieObject$`NAME`
      self$`UNIT` <- ItemBilanEnergieObject$`UNIT`
      self$`LEVEL` <- ItemBilanEnergieObject$`LEVEL`
      self$`DATA_TYPE` <- ItemBilanEnergieObject$`DATA_TYPE`
      self$`FLOW_TYPE` <- ItemBilanEnergieObject$`FLOW_TYPE`
      self
    }
  )
)
