# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ItemStationsEsu
#'
#' @description ItemStationsEsu Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field CODE  character [optional]
#'
#' @field LONGITUDE  numeric [optional]
#'
#' @field LATITUDE  numeric [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ItemStationsEsu <- R6::R6Class(
  'ItemStationsEsu',
  public = list(
    `CODE` = NULL,
    `LONGITUDE` = NULL,
    `LATITUDE` = NULL,
    initialize = function(
        `CODE`=NULL, `LONGITUDE`=NULL, `LATITUDE`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`CODE`)) {
        stopifnot(is.character(`CODE`), length(`CODE`) == 1)
        self$`CODE` <- `CODE`
      }
      if (!is.null(`LONGITUDE`)) {
        self$`LONGITUDE` <- `LONGITUDE`
      }
      if (!is.null(`LATITUDE`)) {
        self$`LATITUDE` <- `LATITUDE`
      }
    },
    toJSON = function() {
      ItemStationsEsuObject <- list()
      if (!is.null(self$`CODE`)) {
        ItemStationsEsuObject[['CODE']] <-
          self$`CODE`
      }
      if (!is.null(self$`LONGITUDE`)) {
        ItemStationsEsuObject[['LONGITUDE']] <-
          self$`LONGITUDE`
      }
      if (!is.null(self$`LATITUDE`)) {
        ItemStationsEsuObject[['LATITUDE']] <-
          self$`LATITUDE`
      }

      ItemStationsEsuObject
    },
    fromJSON = function(ItemStationsEsuJson) {
      ItemStationsEsuObject <- jsonlite::fromJSON(ItemStationsEsuJson)
      if (!is.null(ItemStationsEsuObject$`CODE`)) {
        self$`CODE` <- ItemStationsEsuObject$`CODE`
      }
      if (!is.null(ItemStationsEsuObject$`LONGITUDE`)) {
        self$`LONGITUDE` <- ItemStationsEsuObject$`LONGITUDE`
      }
      if (!is.null(ItemStationsEsuObject$`LATITUDE`)) {
        self$`LATITUDE` <- ItemStationsEsuObject$`LATITUDE`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`CODE`)) {
        sprintf(
        '"CODE":
          "%s"
                ',
        self$`CODE`
        )},
        if (!is.null(self$`LONGITUDE`)) {
        sprintf(
        '"LONGITUDE":
          %d
                ',
        self$`LONGITUDE`
        )},
        if (!is.null(self$`LATITUDE`)) {
        sprintf(
        '"LATITUDE":
          %d
                ',
        self$`LATITUDE`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ItemStationsEsuJson) {
      ItemStationsEsuObject <- jsonlite::fromJSON(ItemStationsEsuJson)
      self$`CODE` <- ItemStationsEsuObject$`CODE`
      self$`LONGITUDE` <- ItemStationsEsuObject$`LONGITUDE`
      self$`LATITUDE` <- ItemStationsEsuObject$`LATITUDE`
      self
    }
  )
)
