# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ItemStationsAir
#'
#' @description ItemStationsAir Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field CODE  character [optional]
#'
#' @field NAME  character [optional]
#'
#' @field CODE_ZAS  character [optional]
#'
#' @field NAME_ZAS  character [optional]
#'
#' @field COMMUNE  character [optional]
#'
#' @field AASQA  character [optional]
#'
#' @field LONGITUDE  numeric [optional]
#'
#' @field LATITUDE  numeric [optional]
#'
#' @field ALTITUDE  numeric [optional]
#'
#' @field VALIDITY_START  character [optional]
#'
#' @field VALIDITY_END  character [optional]
#'
#' @field SECTOR_TYPE  character [optional]
#'
#' @field MILLESIME  numeric [optional]
#'
#' @field IMPACT_PM10  character [optional]
#'
#' @field IMPACT_NO2  character [optional]
#'
#' @field IMPACT_O3  character [optional]
#'
#' @field IMPACT_SO2  character [optional]
#'
#' @field IMPACT_PM25  character [optional]
#'
#' @field IMPACT_CO  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ItemStationsAir <- R6::R6Class(
  'ItemStationsAir',
  public = list(
    `CODE` = NULL,
    `NAME` = NULL,
    `CODE_ZAS` = NULL,
    `NAME_ZAS` = NULL,
    `COMMUNE` = NULL,
    `AASQA` = NULL,
    `LONGITUDE` = NULL,
    `LATITUDE` = NULL,
    `ALTITUDE` = NULL,
    `VALIDITY_START` = NULL,
    `VALIDITY_END` = NULL,
    `SECTOR_TYPE` = NULL,
    `MILLESIME` = NULL,
    `IMPACT_PM10` = NULL,
    `IMPACT_NO2` = NULL,
    `IMPACT_O3` = NULL,
    `IMPACT_SO2` = NULL,
    `IMPACT_PM25` = NULL,
    `IMPACT_CO` = NULL,
    initialize = function(
        `CODE`=NULL, `NAME`=NULL, `CODE_ZAS`=NULL, `NAME_ZAS`=NULL, `COMMUNE`=NULL, `AASQA`=NULL, `LONGITUDE`=NULL, `LATITUDE`=NULL, `ALTITUDE`=NULL, `VALIDITY_START`=NULL, `VALIDITY_END`=NULL, `SECTOR_TYPE`=NULL, `MILLESIME`=NULL, `IMPACT_PM10`=NULL, `IMPACT_NO2`=NULL, `IMPACT_O3`=NULL, `IMPACT_SO2`=NULL, `IMPACT_PM25`=NULL, `IMPACT_CO`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`CODE`)) {
        stopifnot(is.character(`CODE`), length(`CODE`) == 1)
        self$`CODE` <- `CODE`
      }
      if (!is.null(`NAME`)) {
        stopifnot(is.character(`NAME`), length(`NAME`) == 1)
        self$`NAME` <- `NAME`
      }
      if (!is.null(`CODE_ZAS`)) {
        stopifnot(is.character(`CODE_ZAS`), length(`CODE_ZAS`) == 1)
        self$`CODE_ZAS` <- `CODE_ZAS`
      }
      if (!is.null(`NAME_ZAS`)) {
        stopifnot(is.character(`NAME_ZAS`), length(`NAME_ZAS`) == 1)
        self$`NAME_ZAS` <- `NAME_ZAS`
      }
      if (!is.null(`COMMUNE`)) {
        stopifnot(is.character(`COMMUNE`), length(`COMMUNE`) == 1)
        self$`COMMUNE` <- `COMMUNE`
      }
      if (!is.null(`AASQA`)) {
        stopifnot(is.character(`AASQA`), length(`AASQA`) == 1)
        self$`AASQA` <- `AASQA`
      }
      if (!is.null(`LONGITUDE`)) {
        self$`LONGITUDE` <- `LONGITUDE`
      }
      if (!is.null(`LATITUDE`)) {
        self$`LATITUDE` <- `LATITUDE`
      }
      if (!is.null(`ALTITUDE`)) {
        self$`ALTITUDE` <- `ALTITUDE`
      }
      if (!is.null(`VALIDITY_START`)) {
        stopifnot(is.character(`VALIDITY_START`), length(`VALIDITY_START`) == 1)
        self$`VALIDITY_START` <- `VALIDITY_START`
      }
      if (!is.null(`VALIDITY_END`)) {
        stopifnot(is.character(`VALIDITY_END`), length(`VALIDITY_END`) == 1)
        self$`VALIDITY_END` <- `VALIDITY_END`
      }
      if (!is.null(`SECTOR_TYPE`)) {
        stopifnot(is.character(`SECTOR_TYPE`), length(`SECTOR_TYPE`) == 1)
        self$`SECTOR_TYPE` <- `SECTOR_TYPE`
      }
      if (!is.null(`MILLESIME`)) {
        self$`MILLESIME` <- `MILLESIME`
      }
      if (!is.null(`IMPACT_PM10`)) {
        stopifnot(is.character(`IMPACT_PM10`), length(`IMPACT_PM10`) == 1)
        self$`IMPACT_PM10` <- `IMPACT_PM10`
      }
      if (!is.null(`IMPACT_NO2`)) {
        stopifnot(is.character(`IMPACT_NO2`), length(`IMPACT_NO2`) == 1)
        self$`IMPACT_NO2` <- `IMPACT_NO2`
      }
      if (!is.null(`IMPACT_O3`)) {
        stopifnot(is.character(`IMPACT_O3`), length(`IMPACT_O3`) == 1)
        self$`IMPACT_O3` <- `IMPACT_O3`
      }
      if (!is.null(`IMPACT_SO2`)) {
        stopifnot(is.character(`IMPACT_SO2`), length(`IMPACT_SO2`) == 1)
        self$`IMPACT_SO2` <- `IMPACT_SO2`
      }
      if (!is.null(`IMPACT_PM25`)) {
        stopifnot(is.character(`IMPACT_PM25`), length(`IMPACT_PM25`) == 1)
        self$`IMPACT_PM25` <- `IMPACT_PM25`
      }
      if (!is.null(`IMPACT_CO`)) {
        stopifnot(is.character(`IMPACT_CO`), length(`IMPACT_CO`) == 1)
        self$`IMPACT_CO` <- `IMPACT_CO`
      }
    },
    toJSON = function() {
      ItemStationsAirObject <- list()
      if (!is.null(self$`CODE`)) {
        ItemStationsAirObject[['CODE']] <-
          self$`CODE`
      }
      if (!is.null(self$`NAME`)) {
        ItemStationsAirObject[['NAME']] <-
          self$`NAME`
      }
      if (!is.null(self$`CODE_ZAS`)) {
        ItemStationsAirObject[['CODE_ZAS']] <-
          self$`CODE_ZAS`
      }
      if (!is.null(self$`NAME_ZAS`)) {
        ItemStationsAirObject[['NAME_ZAS']] <-
          self$`NAME_ZAS`
      }
      if (!is.null(self$`COMMUNE`)) {
        ItemStationsAirObject[['COMMUNE']] <-
          self$`COMMUNE`
      }
      if (!is.null(self$`AASQA`)) {
        ItemStationsAirObject[['AASQA']] <-
          self$`AASQA`
      }
      if (!is.null(self$`LONGITUDE`)) {
        ItemStationsAirObject[['LONGITUDE']] <-
          self$`LONGITUDE`
      }
      if (!is.null(self$`LATITUDE`)) {
        ItemStationsAirObject[['LATITUDE']] <-
          self$`LATITUDE`
      }
      if (!is.null(self$`ALTITUDE`)) {
        ItemStationsAirObject[['ALTITUDE']] <-
          self$`ALTITUDE`
      }
      if (!is.null(self$`VALIDITY_START`)) {
        ItemStationsAirObject[['VALIDITY_START']] <-
          self$`VALIDITY_START`
      }
      if (!is.null(self$`VALIDITY_END`)) {
        ItemStationsAirObject[['VALIDITY_END']] <-
          self$`VALIDITY_END`
      }
      if (!is.null(self$`SECTOR_TYPE`)) {
        ItemStationsAirObject[['SECTOR_TYPE']] <-
          self$`SECTOR_TYPE`
      }
      if (!is.null(self$`MILLESIME`)) {
        ItemStationsAirObject[['MILLESIME']] <-
          self$`MILLESIME`
      }
      if (!is.null(self$`IMPACT_PM10`)) {
        ItemStationsAirObject[['IMPACT_PM10']] <-
          self$`IMPACT_PM10`
      }
      if (!is.null(self$`IMPACT_NO2`)) {
        ItemStationsAirObject[['IMPACT_NO2']] <-
          self$`IMPACT_NO2`
      }
      if (!is.null(self$`IMPACT_O3`)) {
        ItemStationsAirObject[['IMPACT_O3']] <-
          self$`IMPACT_O3`
      }
      if (!is.null(self$`IMPACT_SO2`)) {
        ItemStationsAirObject[['IMPACT_SO2']] <-
          self$`IMPACT_SO2`
      }
      if (!is.null(self$`IMPACT_PM25`)) {
        ItemStationsAirObject[['IMPACT_PM25']] <-
          self$`IMPACT_PM25`
      }
      if (!is.null(self$`IMPACT_CO`)) {
        ItemStationsAirObject[['IMPACT_CO']] <-
          self$`IMPACT_CO`
      }

      ItemStationsAirObject
    },
    fromJSON = function(ItemStationsAirJson) {
      ItemStationsAirObject <- jsonlite::fromJSON(ItemStationsAirJson)
      if (!is.null(ItemStationsAirObject$`CODE`)) {
        self$`CODE` <- ItemStationsAirObject$`CODE`
      }
      if (!is.null(ItemStationsAirObject$`NAME`)) {
        self$`NAME` <- ItemStationsAirObject$`NAME`
      }
      if (!is.null(ItemStationsAirObject$`CODE_ZAS`)) {
        self$`CODE_ZAS` <- ItemStationsAirObject$`CODE_ZAS`
      }
      if (!is.null(ItemStationsAirObject$`NAME_ZAS`)) {
        self$`NAME_ZAS` <- ItemStationsAirObject$`NAME_ZAS`
      }
      if (!is.null(ItemStationsAirObject$`COMMUNE`)) {
        self$`COMMUNE` <- ItemStationsAirObject$`COMMUNE`
      }
      if (!is.null(ItemStationsAirObject$`AASQA`)) {
        self$`AASQA` <- ItemStationsAirObject$`AASQA`
      }
      if (!is.null(ItemStationsAirObject$`LONGITUDE`)) {
        self$`LONGITUDE` <- ItemStationsAirObject$`LONGITUDE`
      }
      if (!is.null(ItemStationsAirObject$`LATITUDE`)) {
        self$`LATITUDE` <- ItemStationsAirObject$`LATITUDE`
      }
      if (!is.null(ItemStationsAirObject$`ALTITUDE`)) {
        self$`ALTITUDE` <- ItemStationsAirObject$`ALTITUDE`
      }
      if (!is.null(ItemStationsAirObject$`VALIDITY_START`)) {
        self$`VALIDITY_START` <- ItemStationsAirObject$`VALIDITY_START`
      }
      if (!is.null(ItemStationsAirObject$`VALIDITY_END`)) {
        self$`VALIDITY_END` <- ItemStationsAirObject$`VALIDITY_END`
      }
      if (!is.null(ItemStationsAirObject$`SECTOR_TYPE`)) {
        self$`SECTOR_TYPE` <- ItemStationsAirObject$`SECTOR_TYPE`
      }
      if (!is.null(ItemStationsAirObject$`MILLESIME`)) {
        self$`MILLESIME` <- ItemStationsAirObject$`MILLESIME`
      }
      if (!is.null(ItemStationsAirObject$`IMPACT_PM10`)) {
        self$`IMPACT_PM10` <- ItemStationsAirObject$`IMPACT_PM10`
      }
      if (!is.null(ItemStationsAirObject$`IMPACT_NO2`)) {
        self$`IMPACT_NO2` <- ItemStationsAirObject$`IMPACT_NO2`
      }
      if (!is.null(ItemStationsAirObject$`IMPACT_O3`)) {
        self$`IMPACT_O3` <- ItemStationsAirObject$`IMPACT_O3`
      }
      if (!is.null(ItemStationsAirObject$`IMPACT_SO2`)) {
        self$`IMPACT_SO2` <- ItemStationsAirObject$`IMPACT_SO2`
      }
      if (!is.null(ItemStationsAirObject$`IMPACT_PM25`)) {
        self$`IMPACT_PM25` <- ItemStationsAirObject$`IMPACT_PM25`
      }
      if (!is.null(ItemStationsAirObject$`IMPACT_CO`)) {
        self$`IMPACT_CO` <- ItemStationsAirObject$`IMPACT_CO`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`CODE`)) {
        sprintf(
        '"CODE":
          "%s"
                ',
        self$`CODE`
        )},
        if (!is.null(self$`NAME`)) {
        sprintf(
        '"NAME":
          "%s"
                ',
        self$`NAME`
        )},
        if (!is.null(self$`CODE_ZAS`)) {
        sprintf(
        '"CODE_ZAS":
          "%s"
                ',
        self$`CODE_ZAS`
        )},
        if (!is.null(self$`NAME_ZAS`)) {
        sprintf(
        '"NAME_ZAS":
          "%s"
                ',
        self$`NAME_ZAS`
        )},
        if (!is.null(self$`COMMUNE`)) {
        sprintf(
        '"COMMUNE":
          "%s"
                ',
        self$`COMMUNE`
        )},
        if (!is.null(self$`AASQA`)) {
        sprintf(
        '"AASQA":
          "%s"
                ',
        self$`AASQA`
        )},
        if (!is.null(self$`LONGITUDE`)) {
        sprintf(
        '"LONGITUDE":
          %d
                ',
        self$`LONGITUDE`
        )},
        if (!is.null(self$`LATITUDE`)) {
        sprintf(
        '"LATITUDE":
          %d
                ',
        self$`LATITUDE`
        )},
        if (!is.null(self$`ALTITUDE`)) {
        sprintf(
        '"ALTITUDE":
          %d
                ',
        self$`ALTITUDE`
        )},
        if (!is.null(self$`VALIDITY_START`)) {
        sprintf(
        '"VALIDITY_START":
          "%s"
                ',
        self$`VALIDITY_START`
        )},
        if (!is.null(self$`VALIDITY_END`)) {
        sprintf(
        '"VALIDITY_END":
          "%s"
                ',
        self$`VALIDITY_END`
        )},
        if (!is.null(self$`SECTOR_TYPE`)) {
        sprintf(
        '"SECTOR_TYPE":
          "%s"
                ',
        self$`SECTOR_TYPE`
        )},
        if (!is.null(self$`MILLESIME`)) {
        sprintf(
        '"MILLESIME":
          %d
                ',
        self$`MILLESIME`
        )},
        if (!is.null(self$`IMPACT_PM10`)) {
        sprintf(
        '"IMPACT_PM10":
          "%s"
                ',
        self$`IMPACT_PM10`
        )},
        if (!is.null(self$`IMPACT_NO2`)) {
        sprintf(
        '"IMPACT_NO2":
          "%s"
                ',
        self$`IMPACT_NO2`
        )},
        if (!is.null(self$`IMPACT_O3`)) {
        sprintf(
        '"IMPACT_O3":
          "%s"
                ',
        self$`IMPACT_O3`
        )},
        if (!is.null(self$`IMPACT_SO2`)) {
        sprintf(
        '"IMPACT_SO2":
          "%s"
                ',
        self$`IMPACT_SO2`
        )},
        if (!is.null(self$`IMPACT_PM25`)) {
        sprintf(
        '"IMPACT_PM25":
          "%s"
                ',
        self$`IMPACT_PM25`
        )},
        if (!is.null(self$`IMPACT_CO`)) {
        sprintf(
        '"IMPACT_CO":
          "%s"
                ',
        self$`IMPACT_CO`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ItemStationsAirJson) {
      ItemStationsAirObject <- jsonlite::fromJSON(ItemStationsAirJson)
      self$`CODE` <- ItemStationsAirObject$`CODE`
      self$`NAME` <- ItemStationsAirObject$`NAME`
      self$`CODE_ZAS` <- ItemStationsAirObject$`CODE_ZAS`
      self$`NAME_ZAS` <- ItemStationsAirObject$`NAME_ZAS`
      self$`COMMUNE` <- ItemStationsAirObject$`COMMUNE`
      self$`AASQA` <- ItemStationsAirObject$`AASQA`
      self$`LONGITUDE` <- ItemStationsAirObject$`LONGITUDE`
      self$`LATITUDE` <- ItemStationsAirObject$`LATITUDE`
      self$`ALTITUDE` <- ItemStationsAirObject$`ALTITUDE`
      self$`VALIDITY_START` <- ItemStationsAirObject$`VALIDITY_START`
      self$`VALIDITY_END` <- ItemStationsAirObject$`VALIDITY_END`
      self$`SECTOR_TYPE` <- ItemStationsAirObject$`SECTOR_TYPE`
      self$`MILLESIME` <- ItemStationsAirObject$`MILLESIME`
      self$`IMPACT_PM10` <- ItemStationsAirObject$`IMPACT_PM10`
      self$`IMPACT_NO2` <- ItemStationsAirObject$`IMPACT_NO2`
      self$`IMPACT_O3` <- ItemStationsAirObject$`IMPACT_O3`
      self$`IMPACT_SO2` <- ItemStationsAirObject$`IMPACT_SO2`
      self$`IMPACT_PM25` <- ItemStationsAirObject$`IMPACT_PM25`
      self$`IMPACT_CO` <- ItemStationsAirObject$`IMPACT_CO`
      self
    }
  )
)
