# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MillesimeDatafile
#'
#' @description MillesimeDatafile Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field rid  character 
#'
#' @field millesime  character 
#'
#' @field title  character 
#'
#' @field description  character 
#'
#' @field published  character 
#'
#' @field temporal_coverage  \link{DatafileSimpleTemporalCoverage} [optional]
#'
#' @field legal_notice  character [optional]
#'
#' @field weburl  character 
#'
#' @field created_at  character 
#'
#' @field last_modified  character [optional]
#'
#' @field date_diffusion  character 
#'
#' @field dataset  \link{DatasetSimple} 
#'
#' @field previous_millesime_href  character 
#'
#' @field next_millesime_href  character 
#'
#' @field rows  integer 
#'
#' @field columns  list( \link{DatafileSimpleColumns} ) 
#'
#' @field extendedFilters  list( \link{DatafileSimpleExtendedFilters} ) 
#'
#' @field geoFields  list( character ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MillesimeDatafile <- R6::R6Class(
  'MillesimeDatafile',
  public = list(
    `rid` = NULL,
    `millesime` = NULL,
    `title` = NULL,
    `description` = NULL,
    `published` = NULL,
    `temporal_coverage` = NULL,
    `legal_notice` = NULL,
    `weburl` = NULL,
    `created_at` = NULL,
    `last_modified` = NULL,
    `date_diffusion` = NULL,
    `dataset` = NULL,
    `previous_millesime_href` = NULL,
    `next_millesime_href` = NULL,
    `rows` = NULL,
    `columns` = NULL,
    `extendedFilters` = NULL,
    `geoFields` = NULL,
    initialize = function(
        `rid`, `millesime`, `title`, `description`, `published`, `weburl`, `created_at`, `date_diffusion`, `dataset`, `previous_millesime_href`, `next_millesime_href`, `rows`, `columns`, `extendedFilters`, `geoFields`, `temporal_coverage`=NULL, `legal_notice`=NULL, `last_modified`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`rid`)) {
        stopifnot(is.character(`rid`), length(`rid`) == 1)
        self$`rid` <- `rid`
      }
      if (!missing(`millesime`)) {
        stopifnot(is.character(`millesime`), length(`millesime`) == 1)
        self$`millesime` <- `millesime`
      }
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`published`)) {
        stopifnot(is.character(`published`), length(`published`) == 1)
        self$`published` <- `published`
      }
      if (!missing(`weburl`)) {
        stopifnot(is.character(`weburl`), length(`weburl`) == 1)
        self$`weburl` <- `weburl`
      }
      if (!missing(`created_at`)) {
        stopifnot(is.character(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!missing(`date_diffusion`)) {
        stopifnot(is.character(`date_diffusion`), length(`date_diffusion`) == 1)
        self$`date_diffusion` <- `date_diffusion`
      }
      if (!missing(`dataset`)) {
        stopifnot(R6::is.R6(`dataset`))
        self$`dataset` <- `dataset`
      }
      if (!missing(`previous_millesime_href`)) {
        stopifnot(is.character(`previous_millesime_href`), length(`previous_millesime_href`) == 1)
        self$`previous_millesime_href` <- `previous_millesime_href`
      }
      if (!missing(`next_millesime_href`)) {
        stopifnot(is.character(`next_millesime_href`), length(`next_millesime_href`) == 1)
        self$`next_millesime_href` <- `next_millesime_href`
      }
      if (!missing(`rows`)) {
        stopifnot(is.numeric(`rows`), length(`rows`) == 1)
        self$`rows` <- `rows`
      }
      if (!missing(`columns`)) {
        stopifnot(is.vector(`columns`), length(`columns`) != 0)
        sapply(`columns`, function(x) stopifnot(R6::is.R6(x)))
        self$`columns` <- `columns`
      }
      if (!missing(`extendedFilters`)) {
        stopifnot(is.vector(`extendedFilters`), length(`extendedFilters`) != 0)
        sapply(`extendedFilters`, function(x) stopifnot(R6::is.R6(x)))
        self$`extendedFilters` <- `extendedFilters`
      }
      if (!missing(`geoFields`)) {
        stopifnot(is.vector(`geoFields`), length(`geoFields`) != 0)
        sapply(`geoFields`, function(x) stopifnot(is.character(x)))
        self$`geoFields` <- `geoFields`
      }
      if (!is.null(`temporal_coverage`)) {
        stopifnot(R6::is.R6(`temporal_coverage`))
        self$`temporal_coverage` <- `temporal_coverage`
      }
      if (!is.null(`legal_notice`)) {
        stopifnot(is.character(`legal_notice`), length(`legal_notice`) == 1)
        self$`legal_notice` <- `legal_notice`
      }
      if (!is.null(`last_modified`)) {
        stopifnot(is.character(`last_modified`), length(`last_modified`) == 1)
        self$`last_modified` <- `last_modified`
      }
    },
    toJSON = function() {
      MillesimeDatafileObject <- list()
      if (!is.null(self$`rid`)) {
        MillesimeDatafileObject[['rid']] <-
          self$`rid`
      }
      if (!is.null(self$`millesime`)) {
        MillesimeDatafileObject[['millesime']] <-
          self$`millesime`
      }
      if (!is.null(self$`title`)) {
        MillesimeDatafileObject[['title']] <-
          self$`title`
      }
      if (!is.null(self$`description`)) {
        MillesimeDatafileObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`published`)) {
        MillesimeDatafileObject[['published']] <-
          self$`published`
      }
      if (!is.null(self$`temporal_coverage`)) {
        MillesimeDatafileObject[['temporal_coverage']] <-
          self$`temporal_coverage`$toJSON()
      }
      if (!is.null(self$`legal_notice`)) {
        MillesimeDatafileObject[['legal_notice']] <-
          self$`legal_notice`
      }
      if (!is.null(self$`weburl`)) {
        MillesimeDatafileObject[['weburl']] <-
          self$`weburl`
      }
      if (!is.null(self$`created_at`)) {
        MillesimeDatafileObject[['created_at']] <-
          self$`created_at`
      }
      if (!is.null(self$`last_modified`)) {
        MillesimeDatafileObject[['last_modified']] <-
          self$`last_modified`
      }
      if (!is.null(self$`date_diffusion`)) {
        MillesimeDatafileObject[['date_diffusion']] <-
          self$`date_diffusion`
      }
      if (!is.null(self$`dataset`)) {
        MillesimeDatafileObject[['dataset']] <-
          self$`dataset`$toJSON()
      }
      if (!is.null(self$`previous_millesime_href`)) {
        MillesimeDatafileObject[['previous_millesime_href']] <-
          self$`previous_millesime_href`
      }
      if (!is.null(self$`next_millesime_href`)) {
        MillesimeDatafileObject[['next_millesime_href']] <-
          self$`next_millesime_href`
      }
      if (!is.null(self$`rows`)) {
        MillesimeDatafileObject[['rows']] <-
          self$`rows`
      }
      if (!is.null(self$`columns`)) {
        MillesimeDatafileObject[['columns']] <-
          lapply(self$`columns`, function(x) x$toJSON())
      }
      if (!is.null(self$`extendedFilters`)) {
        MillesimeDatafileObject[['extendedFilters']] <-
          lapply(self$`extendedFilters`, function(x) x$toJSON())
      }
      if (!is.null(self$`geoFields`)) {
        MillesimeDatafileObject[['geoFields']] <-
          self$`geoFields`
      }

      MillesimeDatafileObject
    },
    fromJSON = function(MillesimeDatafileJson) {
      MillesimeDatafileObject <- jsonlite::fromJSON(MillesimeDatafileJson)
      if (!is.null(MillesimeDatafileObject$`rid`)) {
        self$`rid` <- MillesimeDatafileObject$`rid`
      }
      if (!is.null(MillesimeDatafileObject$`millesime`)) {
        self$`millesime` <- MillesimeDatafileObject$`millesime`
      }
      if (!is.null(MillesimeDatafileObject$`title`)) {
        self$`title` <- MillesimeDatafileObject$`title`
      }
      if (!is.null(MillesimeDatafileObject$`description`)) {
        self$`description` <- MillesimeDatafileObject$`description`
      }
      if (!is.null(MillesimeDatafileObject$`published`)) {
        self$`published` <- MillesimeDatafileObject$`published`
      }
      if (!is.null(MillesimeDatafileObject$`temporal_coverage`)) {
        temporal_coverageObject <- DatafileSimpleTemporalCoverage$new()
        temporal_coverageObject$fromJSON(jsonlite::toJSON(MillesimeDatafileObject$temporal_coverage, auto_unbox = TRUE, digits = NA))
        self$`temporal_coverage` <- temporal_coverageObject
      }
      if (!is.null(MillesimeDatafileObject$`legal_notice`)) {
        self$`legal_notice` <- MillesimeDatafileObject$`legal_notice`
      }
      if (!is.null(MillesimeDatafileObject$`weburl`)) {
        self$`weburl` <- MillesimeDatafileObject$`weburl`
      }
      if (!is.null(MillesimeDatafileObject$`created_at`)) {
        self$`created_at` <- MillesimeDatafileObject$`created_at`
      }
      if (!is.null(MillesimeDatafileObject$`last_modified`)) {
        self$`last_modified` <- MillesimeDatafileObject$`last_modified`
      }
      if (!is.null(MillesimeDatafileObject$`date_diffusion`)) {
        self$`date_diffusion` <- MillesimeDatafileObject$`date_diffusion`
      }
      if (!is.null(MillesimeDatafileObject$`dataset`)) {
        datasetObject <- DatasetSimple$new()
        datasetObject$fromJSON(jsonlite::toJSON(MillesimeDatafileObject$dataset, auto_unbox = TRUE, digits = NA))
        self$`dataset` <- datasetObject
      }
      if (!is.null(MillesimeDatafileObject$`previous_millesime_href`)) {
        self$`previous_millesime_href` <- MillesimeDatafileObject$`previous_millesime_href`
      }
      if (!is.null(MillesimeDatafileObject$`next_millesime_href`)) {
        self$`next_millesime_href` <- MillesimeDatafileObject$`next_millesime_href`
      }
      if (!is.null(MillesimeDatafileObject$`rows`)) {
        self$`rows` <- MillesimeDatafileObject$`rows`
      }
      if (!is.null(MillesimeDatafileObject$`columns`)) {
        self$`columns` <- ApiClient$new()$deserializeObj(MillesimeDatafileObject$`columns`, "array[DatafileSimpleColumns]", loadNamespace("didoscalie"))
      }
      if (!is.null(MillesimeDatafileObject$`extendedFilters`)) {
        self$`extendedFilters` <- ApiClient$new()$deserializeObj(MillesimeDatafileObject$`extendedFilters`, "array[DatafileSimpleExtendedFilters]", loadNamespace("didoscalie"))
      }
      if (!is.null(MillesimeDatafileObject$`geoFields`)) {
        self$`geoFields` <- ApiClient$new()$deserializeObj(MillesimeDatafileObject$`geoFields`, "array[character]", loadNamespace("didoscalie"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`rid`)) {
        sprintf(
        '"rid":
          "%s"
                ',
        self$`rid`
        )},
        if (!is.null(self$`millesime`)) {
        sprintf(
        '"millesime":
          "%s"
                ',
        self$`millesime`
        )},
        if (!is.null(self$`title`)) {
        sprintf(
        '"title":
          "%s"
                ',
        self$`title`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`published`)) {
        sprintf(
        '"published":
          "%s"
                ',
        self$`published`
        )},
        if (!is.null(self$`temporal_coverage`)) {
        sprintf(
        '"temporal_coverage":
        %s
        ',
        jsonlite::toJSON(self$`temporal_coverage`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`legal_notice`)) {
        sprintf(
        '"legal_notice":
          "%s"
                ',
        self$`legal_notice`
        )},
        if (!is.null(self$`weburl`)) {
        sprintf(
        '"weburl":
          "%s"
                ',
        self$`weburl`
        )},
        if (!is.null(self$`created_at`)) {
        sprintf(
        '"created_at":
          "%s"
                ',
        self$`created_at`
        )},
        if (!is.null(self$`last_modified`)) {
        sprintf(
        '"last_modified":
          "%s"
                ',
        self$`last_modified`
        )},
        if (!is.null(self$`date_diffusion`)) {
        sprintf(
        '"date_diffusion":
          "%s"
                ',
        self$`date_diffusion`
        )},
        if (!is.null(self$`dataset`)) {
        sprintf(
        '"dataset":
        %s
        ',
        jsonlite::toJSON(self$`dataset`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`previous_millesime_href`)) {
        sprintf(
        '"previous_millesime_href":
          "%s"
                ',
        self$`previous_millesime_href`
        )},
        if (!is.null(self$`next_millesime_href`)) {
        sprintf(
        '"next_millesime_href":
          "%s"
                ',
        self$`next_millesime_href`
        )},
        if (!is.null(self$`rows`)) {
        sprintf(
        '"rows":
          %d
                ',
        self$`rows`
        )},
        if (!is.null(self$`columns`)) {
        sprintf(
        '"columns":
        [%s]
',
        paste(sapply(self$`columns`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`extendedFilters`)) {
        sprintf(
        '"extendedFilters":
        [%s]
',
        paste(sapply(self$`extendedFilters`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`geoFields`)) {
        sprintf(
        '"geoFields":
           [%s]
        ',
        paste(unlist(lapply(self$`geoFields`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MillesimeDatafileJson) {
      MillesimeDatafileObject <- jsonlite::fromJSON(MillesimeDatafileJson)
      self$`rid` <- MillesimeDatafileObject$`rid`
      self$`millesime` <- MillesimeDatafileObject$`millesime`
      self$`title` <- MillesimeDatafileObject$`title`
      self$`description` <- MillesimeDatafileObject$`description`
      self$`published` <- MillesimeDatafileObject$`published`
      self$`temporal_coverage` <- DatafileSimpleTemporalCoverage$new()$fromJSON(jsonlite::toJSON(MillesimeDatafileObject$temporal_coverage, auto_unbox = TRUE, digits = NA))
      self$`legal_notice` <- MillesimeDatafileObject$`legal_notice`
      self$`weburl` <- MillesimeDatafileObject$`weburl`
      self$`created_at` <- MillesimeDatafileObject$`created_at`
      self$`last_modified` <- MillesimeDatafileObject$`last_modified`
      self$`date_diffusion` <- MillesimeDatafileObject$`date_diffusion`
      self$`dataset` <- DatasetSimple$new()$fromJSON(jsonlite::toJSON(MillesimeDatafileObject$dataset, auto_unbox = TRUE, digits = NA))
      self$`previous_millesime_href` <- MillesimeDatafileObject$`previous_millesime_href`
      self$`next_millesime_href` <- MillesimeDatafileObject$`next_millesime_href`
      self$`rows` <- MillesimeDatafileObject$`rows`
      self$`columns` <- ApiClient$new()$deserializeObj(MillesimeDatafileObject$`columns`, "array[DatafileSimpleColumns]", loadNamespace("didoscalie"))
      self$`extendedFilters` <- ApiClient$new()$deserializeObj(MillesimeDatafileObject$`extendedFilters`, "array[DatafileSimpleExtendedFilters]", loadNamespace("didoscalie"))
      self$`geoFields` <- ApiClient$new()$deserializeObj(MillesimeDatafileObject$`geoFields`, "array[character]", loadNamespace("didoscalie"))
      self
    }
  )
)
