# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MillesimeDatafileNoData
#'
#' @description MillesimeDatafileNoData Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field rid  character 
#'
#' @field millesime  character 
#'
#' @field title  character 
#'
#' @field description  character 
#'
#' @field published  character 
#'
#' @field temporal_coverage  \link{DatafileSimpleTemporalCoverage} [optional]
#'
#' @field legal_notice  character [optional]
#'
#' @field weburl  character 
#'
#' @field created_at  character 
#'
#' @field last_modified  character [optional]
#'
#' @field date_diffusion  character 
#'
#' @field dataset  \link{DatasetSimple} 
#'
#' @field previous_millesime_href  character 
#'
#' @field next_millesime_href  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MillesimeDatafileNoData <- R6::R6Class(
  'MillesimeDatafileNoData',
  public = list(
    `rid` = NULL,
    `millesime` = NULL,
    `title` = NULL,
    `description` = NULL,
    `published` = NULL,
    `temporal_coverage` = NULL,
    `legal_notice` = NULL,
    `weburl` = NULL,
    `created_at` = NULL,
    `last_modified` = NULL,
    `date_diffusion` = NULL,
    `dataset` = NULL,
    `previous_millesime_href` = NULL,
    `next_millesime_href` = NULL,
    initialize = function(
        `rid`, `millesime`, `title`, `description`, `published`, `weburl`, `created_at`, `date_diffusion`, `dataset`, `previous_millesime_href`, `next_millesime_href`, `temporal_coverage`=NULL, `legal_notice`=NULL, `last_modified`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`rid`)) {
        stopifnot(is.character(`rid`), length(`rid`) == 1)
        self$`rid` <- `rid`
      }
      if (!missing(`millesime`)) {
        stopifnot(is.character(`millesime`), length(`millesime`) == 1)
        self$`millesime` <- `millesime`
      }
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`published`)) {
        stopifnot(is.character(`published`), length(`published`) == 1)
        self$`published` <- `published`
      }
      if (!missing(`weburl`)) {
        stopifnot(is.character(`weburl`), length(`weburl`) == 1)
        self$`weburl` <- `weburl`
      }
      if (!missing(`created_at`)) {
        stopifnot(is.character(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!missing(`date_diffusion`)) {
        stopifnot(is.character(`date_diffusion`), length(`date_diffusion`) == 1)
        self$`date_diffusion` <- `date_diffusion`
      }
      if (!missing(`dataset`)) {
        stopifnot(R6::is.R6(`dataset`))
        self$`dataset` <- `dataset`
      }
      if (!missing(`previous_millesime_href`)) {
        stopifnot(is.character(`previous_millesime_href`), length(`previous_millesime_href`) == 1)
        self$`previous_millesime_href` <- `previous_millesime_href`
      }
      if (!missing(`next_millesime_href`)) {
        stopifnot(is.character(`next_millesime_href`), length(`next_millesime_href`) == 1)
        self$`next_millesime_href` <- `next_millesime_href`
      }
      if (!is.null(`temporal_coverage`)) {
        stopifnot(R6::is.R6(`temporal_coverage`))
        self$`temporal_coverage` <- `temporal_coverage`
      }
      if (!is.null(`legal_notice`)) {
        stopifnot(is.character(`legal_notice`), length(`legal_notice`) == 1)
        self$`legal_notice` <- `legal_notice`
      }
      if (!is.null(`last_modified`)) {
        stopifnot(is.character(`last_modified`), length(`last_modified`) == 1)
        self$`last_modified` <- `last_modified`
      }
    },
    toJSON = function() {
      MillesimeDatafileNoDataObject <- list()
      if (!is.null(self$`rid`)) {
        MillesimeDatafileNoDataObject[['rid']] <-
          self$`rid`
      }
      if (!is.null(self$`millesime`)) {
        MillesimeDatafileNoDataObject[['millesime']] <-
          self$`millesime`
      }
      if (!is.null(self$`title`)) {
        MillesimeDatafileNoDataObject[['title']] <-
          self$`title`
      }
      if (!is.null(self$`description`)) {
        MillesimeDatafileNoDataObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`published`)) {
        MillesimeDatafileNoDataObject[['published']] <-
          self$`published`
      }
      if (!is.null(self$`temporal_coverage`)) {
        MillesimeDatafileNoDataObject[['temporal_coverage']] <-
          self$`temporal_coverage`$toJSON()
      }
      if (!is.null(self$`legal_notice`)) {
        MillesimeDatafileNoDataObject[['legal_notice']] <-
          self$`legal_notice`
      }
      if (!is.null(self$`weburl`)) {
        MillesimeDatafileNoDataObject[['weburl']] <-
          self$`weburl`
      }
      if (!is.null(self$`created_at`)) {
        MillesimeDatafileNoDataObject[['created_at']] <-
          self$`created_at`
      }
      if (!is.null(self$`last_modified`)) {
        MillesimeDatafileNoDataObject[['last_modified']] <-
          self$`last_modified`
      }
      if (!is.null(self$`date_diffusion`)) {
        MillesimeDatafileNoDataObject[['date_diffusion']] <-
          self$`date_diffusion`
      }
      if (!is.null(self$`dataset`)) {
        MillesimeDatafileNoDataObject[['dataset']] <-
          self$`dataset`$toJSON()
      }
      if (!is.null(self$`previous_millesime_href`)) {
        MillesimeDatafileNoDataObject[['previous_millesime_href']] <-
          self$`previous_millesime_href`
      }
      if (!is.null(self$`next_millesime_href`)) {
        MillesimeDatafileNoDataObject[['next_millesime_href']] <-
          self$`next_millesime_href`
      }

      MillesimeDatafileNoDataObject
    },
    fromJSON = function(MillesimeDatafileNoDataJson) {
      MillesimeDatafileNoDataObject <- jsonlite::fromJSON(MillesimeDatafileNoDataJson)
      if (!is.null(MillesimeDatafileNoDataObject$`rid`)) {
        self$`rid` <- MillesimeDatafileNoDataObject$`rid`
      }
      if (!is.null(MillesimeDatafileNoDataObject$`millesime`)) {
        self$`millesime` <- MillesimeDatafileNoDataObject$`millesime`
      }
      if (!is.null(MillesimeDatafileNoDataObject$`title`)) {
        self$`title` <- MillesimeDatafileNoDataObject$`title`
      }
      if (!is.null(MillesimeDatafileNoDataObject$`description`)) {
        self$`description` <- MillesimeDatafileNoDataObject$`description`
      }
      if (!is.null(MillesimeDatafileNoDataObject$`published`)) {
        self$`published` <- MillesimeDatafileNoDataObject$`published`
      }
      if (!is.null(MillesimeDatafileNoDataObject$`temporal_coverage`)) {
        temporal_coverageObject <- DatafileSimpleTemporalCoverage$new()
        temporal_coverageObject$fromJSON(jsonlite::toJSON(MillesimeDatafileNoDataObject$temporal_coverage, auto_unbox = TRUE, digits = NA))
        self$`temporal_coverage` <- temporal_coverageObject
      }
      if (!is.null(MillesimeDatafileNoDataObject$`legal_notice`)) {
        self$`legal_notice` <- MillesimeDatafileNoDataObject$`legal_notice`
      }
      if (!is.null(MillesimeDatafileNoDataObject$`weburl`)) {
        self$`weburl` <- MillesimeDatafileNoDataObject$`weburl`
      }
      if (!is.null(MillesimeDatafileNoDataObject$`created_at`)) {
        self$`created_at` <- MillesimeDatafileNoDataObject$`created_at`
      }
      if (!is.null(MillesimeDatafileNoDataObject$`last_modified`)) {
        self$`last_modified` <- MillesimeDatafileNoDataObject$`last_modified`
      }
      if (!is.null(MillesimeDatafileNoDataObject$`date_diffusion`)) {
        self$`date_diffusion` <- MillesimeDatafileNoDataObject$`date_diffusion`
      }
      if (!is.null(MillesimeDatafileNoDataObject$`dataset`)) {
        datasetObject <- DatasetSimple$new()
        datasetObject$fromJSON(jsonlite::toJSON(MillesimeDatafileNoDataObject$dataset, auto_unbox = TRUE, digits = NA))
        self$`dataset` <- datasetObject
      }
      if (!is.null(MillesimeDatafileNoDataObject$`previous_millesime_href`)) {
        self$`previous_millesime_href` <- MillesimeDatafileNoDataObject$`previous_millesime_href`
      }
      if (!is.null(MillesimeDatafileNoDataObject$`next_millesime_href`)) {
        self$`next_millesime_href` <- MillesimeDatafileNoDataObject$`next_millesime_href`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`rid`)) {
        sprintf(
        '"rid":
          "%s"
                ',
        self$`rid`
        )},
        if (!is.null(self$`millesime`)) {
        sprintf(
        '"millesime":
          "%s"
                ',
        self$`millesime`
        )},
        if (!is.null(self$`title`)) {
        sprintf(
        '"title":
          "%s"
                ',
        self$`title`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`published`)) {
        sprintf(
        '"published":
          "%s"
                ',
        self$`published`
        )},
        if (!is.null(self$`temporal_coverage`)) {
        sprintf(
        '"temporal_coverage":
        %s
        ',
        jsonlite::toJSON(self$`temporal_coverage`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`legal_notice`)) {
        sprintf(
        '"legal_notice":
          "%s"
                ',
        self$`legal_notice`
        )},
        if (!is.null(self$`weburl`)) {
        sprintf(
        '"weburl":
          "%s"
                ',
        self$`weburl`
        )},
        if (!is.null(self$`created_at`)) {
        sprintf(
        '"created_at":
          "%s"
                ',
        self$`created_at`
        )},
        if (!is.null(self$`last_modified`)) {
        sprintf(
        '"last_modified":
          "%s"
                ',
        self$`last_modified`
        )},
        if (!is.null(self$`date_diffusion`)) {
        sprintf(
        '"date_diffusion":
          "%s"
                ',
        self$`date_diffusion`
        )},
        if (!is.null(self$`dataset`)) {
        sprintf(
        '"dataset":
        %s
        ',
        jsonlite::toJSON(self$`dataset`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`previous_millesime_href`)) {
        sprintf(
        '"previous_millesime_href":
          "%s"
                ',
        self$`previous_millesime_href`
        )},
        if (!is.null(self$`next_millesime_href`)) {
        sprintf(
        '"next_millesime_href":
          "%s"
                ',
        self$`next_millesime_href`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MillesimeDatafileNoDataJson) {
      MillesimeDatafileNoDataObject <- jsonlite::fromJSON(MillesimeDatafileNoDataJson)
      self$`rid` <- MillesimeDatafileNoDataObject$`rid`
      self$`millesime` <- MillesimeDatafileNoDataObject$`millesime`
      self$`title` <- MillesimeDatafileNoDataObject$`title`
      self$`description` <- MillesimeDatafileNoDataObject$`description`
      self$`published` <- MillesimeDatafileNoDataObject$`published`
      self$`temporal_coverage` <- DatafileSimpleTemporalCoverage$new()$fromJSON(jsonlite::toJSON(MillesimeDatafileNoDataObject$temporal_coverage, auto_unbox = TRUE, digits = NA))
      self$`legal_notice` <- MillesimeDatafileNoDataObject$`legal_notice`
      self$`weburl` <- MillesimeDatafileNoDataObject$`weburl`
      self$`created_at` <- MillesimeDatafileNoDataObject$`created_at`
      self$`last_modified` <- MillesimeDatafileNoDataObject$`last_modified`
      self$`date_diffusion` <- MillesimeDatafileNoDataObject$`date_diffusion`
      self$`dataset` <- DatasetSimple$new()$fromJSON(jsonlite::toJSON(MillesimeDatafileNoDataObject$dataset, auto_unbox = TRUE, digits = NA))
      self$`previous_millesime_href` <- MillesimeDatafileNoDataObject$`previous_millesime_href`
      self$`next_millesime_href` <- MillesimeDatafileNoDataObject$`next_millesime_href`
      self
    }
  )
)
