# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MillesimeDatafileAllOf
#'
#' @description MillesimeDatafileAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field rows  integer 
#'
#' @field columns  list( \link{DatafileSimpleColumns} ) 
#'
#' @field extendedFilters  list( \link{DatafileSimpleExtendedFilters} ) 
#'
#' @field geoFields  list( character ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MillesimeDatafileAllOf <- R6::R6Class(
  'MillesimeDatafileAllOf',
  public = list(
    `rows` = NULL,
    `columns` = NULL,
    `extendedFilters` = NULL,
    `geoFields` = NULL,
    initialize = function(
        `rows`, `columns`, `extendedFilters`, `geoFields`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`rows`)) {
        stopifnot(is.numeric(`rows`), length(`rows`) == 1)
        self$`rows` <- `rows`
      }
      if (!missing(`columns`)) {
        stopifnot(is.vector(`columns`), length(`columns`) != 0)
        sapply(`columns`, function(x) stopifnot(R6::is.R6(x)))
        self$`columns` <- `columns`
      }
      if (!missing(`extendedFilters`)) {
        stopifnot(is.vector(`extendedFilters`), length(`extendedFilters`) != 0)
        sapply(`extendedFilters`, function(x) stopifnot(R6::is.R6(x)))
        self$`extendedFilters` <- `extendedFilters`
      }
      if (!missing(`geoFields`)) {
        stopifnot(is.vector(`geoFields`), length(`geoFields`) != 0)
        sapply(`geoFields`, function(x) stopifnot(is.character(x)))
        self$`geoFields` <- `geoFields`
      }
    },
    toJSON = function() {
      MillesimeDatafileAllOfObject <- list()
      if (!is.null(self$`rows`)) {
        MillesimeDatafileAllOfObject[['rows']] <-
          self$`rows`
      }
      if (!is.null(self$`columns`)) {
        MillesimeDatafileAllOfObject[['columns']] <-
          lapply(self$`columns`, function(x) x$toJSON())
      }
      if (!is.null(self$`extendedFilters`)) {
        MillesimeDatafileAllOfObject[['extendedFilters']] <-
          lapply(self$`extendedFilters`, function(x) x$toJSON())
      }
      if (!is.null(self$`geoFields`)) {
        MillesimeDatafileAllOfObject[['geoFields']] <-
          self$`geoFields`
      }

      MillesimeDatafileAllOfObject
    },
    fromJSON = function(MillesimeDatafileAllOfJson) {
      MillesimeDatafileAllOfObject <- jsonlite::fromJSON(MillesimeDatafileAllOfJson)
      if (!is.null(MillesimeDatafileAllOfObject$`rows`)) {
        self$`rows` <- MillesimeDatafileAllOfObject$`rows`
      }
      if (!is.null(MillesimeDatafileAllOfObject$`columns`)) {
        self$`columns` <- ApiClient$new()$deserializeObj(MillesimeDatafileAllOfObject$`columns`, "array[DatafileSimpleColumns]", loadNamespace("didoscalie"))
      }
      if (!is.null(MillesimeDatafileAllOfObject$`extendedFilters`)) {
        self$`extendedFilters` <- ApiClient$new()$deserializeObj(MillesimeDatafileAllOfObject$`extendedFilters`, "array[DatafileSimpleExtendedFilters]", loadNamespace("didoscalie"))
      }
      if (!is.null(MillesimeDatafileAllOfObject$`geoFields`)) {
        self$`geoFields` <- ApiClient$new()$deserializeObj(MillesimeDatafileAllOfObject$`geoFields`, "array[character]", loadNamespace("didoscalie"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`rows`)) {
        sprintf(
        '"rows":
          %d
                ',
        self$`rows`
        )},
        if (!is.null(self$`columns`)) {
        sprintf(
        '"columns":
        [%s]
',
        paste(sapply(self$`columns`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`extendedFilters`)) {
        sprintf(
        '"extendedFilters":
        [%s]
',
        paste(sapply(self$`extendedFilters`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`geoFields`)) {
        sprintf(
        '"geoFields":
           [%s]
        ',
        paste(unlist(lapply(self$`geoFields`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MillesimeDatafileAllOfJson) {
      MillesimeDatafileAllOfObject <- jsonlite::fromJSON(MillesimeDatafileAllOfJson)
      self$`rows` <- MillesimeDatafileAllOfObject$`rows`
      self$`columns` <- ApiClient$new()$deserializeObj(MillesimeDatafileAllOfObject$`columns`, "array[DatafileSimpleColumns]", loadNamespace("didoscalie"))
      self$`extendedFilters` <- ApiClient$new()$deserializeObj(MillesimeDatafileAllOfObject$`extendedFilters`, "array[DatafileSimpleExtendedFilters]", loadNamespace("didoscalie"))
      self$`geoFields` <- ApiClient$new()$deserializeObj(MillesimeDatafileAllOfObject$`geoFields`, "array[character]", loadNamespace("didoscalie"))
      self
    }
  )
)
