# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PaginateListPortsAllOf
#'
#' @description PaginateListPortsAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field data  list( \link{ItemPorts} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PaginateListPortsAllOf <- R6::R6Class(
  'PaginateListPortsAllOf',
  public = list(
    `data` = NULL,
    initialize = function(
        `data`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`data`)) {
        stopifnot(is.vector(`data`), length(`data`) != 0)
        sapply(`data`, function(x) stopifnot(R6::is.R6(x)))
        self$`data` <- `data`
      }
    },
    toJSON = function() {
      PaginateListPortsAllOfObject <- list()
      if (!is.null(self$`data`)) {
        PaginateListPortsAllOfObject[['data']] <-
          lapply(self$`data`, function(x) x$toJSON())
      }

      PaginateListPortsAllOfObject
    },
    fromJSON = function(PaginateListPortsAllOfJson) {
      PaginateListPortsAllOfObject <- jsonlite::fromJSON(PaginateListPortsAllOfJson)
      if (!is.null(PaginateListPortsAllOfObject$`data`)) {
        self$`data` <- ApiClient$new()$deserializeObj(PaginateListPortsAllOfObject$`data`, "array[ItemPorts]", loadNamespace("didoscalie"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`data`)) {
        sprintf(
        '"data":
        [%s]
',
        paste(sapply(self$`data`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PaginateListPortsAllOfJson) {
      PaginateListPortsAllOfObject <- jsonlite::fromJSON(PaginateListPortsAllOfJson)
      self$`data` <- ApiClient$new()$deserializeObj(PaginateListPortsAllOfObject$`data`, "array[ItemPorts]", loadNamespace("didoscalie"))
      self
    }
  )
)
