# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PaginateListRows
#'
#' @description PaginateListRows Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field pageSize  character 
#'
#' @field page  integer 
#'
#' @field total  integer 
#'
#' @field firstPage  character 
#'
#' @field previousPage  character 
#'
#' @field nextPage  character 
#'
#' @field lastPage  character 
#'
#' @field data  list( object ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PaginateListRows <- R6::R6Class(
  'PaginateListRows',
  public = list(
    `pageSize` = NULL,
    `page` = NULL,
    `total` = NULL,
    `firstPage` = NULL,
    `previousPage` = NULL,
    `nextPage` = NULL,
    `lastPage` = NULL,
    `data` = NULL,
    initialize = function(
        `pageSize`, `page`, `total`, `firstPage`, `previousPage`, `nextPage`, `lastPage`, `data`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`pageSize`)) {
        stopifnot(is.character(`pageSize`), length(`pageSize`) == 1)
        self$`pageSize` <- `pageSize`
      }
      if (!missing(`page`)) {
        stopifnot(is.numeric(`page`), length(`page`) == 1)
        self$`page` <- `page`
      }
      if (!missing(`total`)) {
        stopifnot(is.numeric(`total`), length(`total`) == 1)
        self$`total` <- `total`
      }
      if (!missing(`firstPage`)) {
        stopifnot(is.character(`firstPage`), length(`firstPage`) == 1)
        self$`firstPage` <- `firstPage`
      }
      if (!missing(`previousPage`)) {
        stopifnot(is.character(`previousPage`), length(`previousPage`) == 1)
        self$`previousPage` <- `previousPage`
      }
      if (!missing(`nextPage`)) {
        stopifnot(is.character(`nextPage`), length(`nextPage`) == 1)
        self$`nextPage` <- `nextPage`
      }
      if (!missing(`lastPage`)) {
        stopifnot(is.character(`lastPage`), length(`lastPage`) == 1)
        self$`lastPage` <- `lastPage`
      }
      if (!missing(`data`)) {
        stopifnot(is.vector(`data`), length(`data`) != 0)
        sapply(`data`, function(x) stopifnot(is.character(x)))
        self$`data` <- `data`
      }
    },
    toJSON = function() {
      PaginateListRowsObject <- list()
      if (!is.null(self$`pageSize`)) {
        PaginateListRowsObject[['pageSize']] <-
          self$`pageSize`
      }
      if (!is.null(self$`page`)) {
        PaginateListRowsObject[['page']] <-
          self$`page`
      }
      if (!is.null(self$`total`)) {
        PaginateListRowsObject[['total']] <-
          self$`total`
      }
      if (!is.null(self$`firstPage`)) {
        PaginateListRowsObject[['firstPage']] <-
          self$`firstPage`
      }
      if (!is.null(self$`previousPage`)) {
        PaginateListRowsObject[['previousPage']] <-
          self$`previousPage`
      }
      if (!is.null(self$`nextPage`)) {
        PaginateListRowsObject[['nextPage']] <-
          self$`nextPage`
      }
      if (!is.null(self$`lastPage`)) {
        PaginateListRowsObject[['lastPage']] <-
          self$`lastPage`
      }
      if (!is.null(self$`data`)) {
        PaginateListRowsObject[['data']] <-
          self$`data`
      }

      PaginateListRowsObject
    },
    fromJSON = function(PaginateListRowsJson) {
      PaginateListRowsObject <- jsonlite::fromJSON(PaginateListRowsJson)
      if (!is.null(PaginateListRowsObject$`pageSize`)) {
        self$`pageSize` <- PaginateListRowsObject$`pageSize`
      }
      if (!is.null(PaginateListRowsObject$`page`)) {
        self$`page` <- PaginateListRowsObject$`page`
      }
      if (!is.null(PaginateListRowsObject$`total`)) {
        self$`total` <- PaginateListRowsObject$`total`
      }
      if (!is.null(PaginateListRowsObject$`firstPage`)) {
        self$`firstPage` <- PaginateListRowsObject$`firstPage`
      }
      if (!is.null(PaginateListRowsObject$`previousPage`)) {
        self$`previousPage` <- PaginateListRowsObject$`previousPage`
      }
      if (!is.null(PaginateListRowsObject$`nextPage`)) {
        self$`nextPage` <- PaginateListRowsObject$`nextPage`
      }
      if (!is.null(PaginateListRowsObject$`lastPage`)) {
        self$`lastPage` <- PaginateListRowsObject$`lastPage`
      }
      if (!is.null(PaginateListRowsObject$`data`)) {
        self$`data` <- ApiClient$new()$deserializeObj(PaginateListRowsObject$`data`, "array[object]", loadNamespace("didoscalie"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`pageSize`)) {
        sprintf(
        '"pageSize":
          "%s"
                ',
        self$`pageSize`
        )},
        if (!is.null(self$`page`)) {
        sprintf(
        '"page":
          %d
                ',
        self$`page`
        )},
        if (!is.null(self$`total`)) {
        sprintf(
        '"total":
          %d
                ',
        self$`total`
        )},
        if (!is.null(self$`firstPage`)) {
        sprintf(
        '"firstPage":
          "%s"
                ',
        self$`firstPage`
        )},
        if (!is.null(self$`previousPage`)) {
        sprintf(
        '"previousPage":
          "%s"
                ',
        self$`previousPage`
        )},
        if (!is.null(self$`nextPage`)) {
        sprintf(
        '"nextPage":
          "%s"
                ',
        self$`nextPage`
        )},
        if (!is.null(self$`lastPage`)) {
        sprintf(
        '"lastPage":
          "%s"
                ',
        self$`lastPage`
        )},
        if (!is.null(self$`data`)) {
        sprintf(
        '"data":
           [%s]
        ',
        paste(unlist(lapply(self$`data`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PaginateListRowsJson) {
      PaginateListRowsObject <- jsonlite::fromJSON(PaginateListRowsJson)
      self$`pageSize` <- PaginateListRowsObject$`pageSize`
      self$`page` <- PaginateListRowsObject$`page`
      self$`total` <- PaginateListRowsObject$`total`
      self$`firstPage` <- PaginateListRowsObject$`firstPage`
      self$`previousPage` <- PaginateListRowsObject$`previousPage`
      self$`nextPage` <- PaginateListRowsObject$`nextPage`
      self$`lastPage` <- PaginateListRowsObject$`lastPage`
      self$`data` <- ApiClient$new()$deserializeObj(PaginateListRowsObject$`data`, "array[object]", loadNamespace("didoscalie"))
      self
    }
  )
)
