# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PaginateListDatafiles
#'
#' @description PaginateListDatafiles Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field pageSize  character 
#'
#' @field page  integer 
#'
#' @field total  integer 
#'
#' @field firstPage  character 
#'
#' @field previousPage  character 
#'
#' @field nextPage  character 
#'
#' @field lastPage  character 
#'
#' @field data  list( \link{DatafileFull} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PaginateListDatafiles <- R6::R6Class(
  'PaginateListDatafiles',
  public = list(
    `pageSize` = NULL,
    `page` = NULL,
    `total` = NULL,
    `firstPage` = NULL,
    `previousPage` = NULL,
    `nextPage` = NULL,
    `lastPage` = NULL,
    `data` = NULL,
    initialize = function(
        `pageSize`, `page`, `total`, `firstPage`, `previousPage`, `nextPage`, `lastPage`, `data`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`pageSize`)) {
        stopifnot(is.character(`pageSize`), length(`pageSize`) == 1)
        self$`pageSize` <- `pageSize`
      }
      if (!missing(`page`)) {
        stopifnot(is.numeric(`page`), length(`page`) == 1)
        self$`page` <- `page`
      }
      if (!missing(`total`)) {
        stopifnot(is.numeric(`total`), length(`total`) == 1)
        self$`total` <- `total`
      }
      if (!missing(`firstPage`)) {
        stopifnot(is.character(`firstPage`), length(`firstPage`) == 1)
        self$`firstPage` <- `firstPage`
      }
      if (!missing(`previousPage`)) {
        stopifnot(is.character(`previousPage`), length(`previousPage`) == 1)
        self$`previousPage` <- `previousPage`
      }
      if (!missing(`nextPage`)) {
        stopifnot(is.character(`nextPage`), length(`nextPage`) == 1)
        self$`nextPage` <- `nextPage`
      }
      if (!missing(`lastPage`)) {
        stopifnot(is.character(`lastPage`), length(`lastPage`) == 1)
        self$`lastPage` <- `lastPage`
      }
      if (!missing(`data`)) {
        stopifnot(is.vector(`data`), length(`data`) != 0)
        sapply(`data`, function(x) stopifnot(R6::is.R6(x)))
        self$`data` <- `data`
      }
    },
    toJSON = function() {
      PaginateListDatafilesObject <- list()
      if (!is.null(self$`pageSize`)) {
        PaginateListDatafilesObject[['pageSize']] <-
          self$`pageSize`
      }
      if (!is.null(self$`page`)) {
        PaginateListDatafilesObject[['page']] <-
          self$`page`
      }
      if (!is.null(self$`total`)) {
        PaginateListDatafilesObject[['total']] <-
          self$`total`
      }
      if (!is.null(self$`firstPage`)) {
        PaginateListDatafilesObject[['firstPage']] <-
          self$`firstPage`
      }
      if (!is.null(self$`previousPage`)) {
        PaginateListDatafilesObject[['previousPage']] <-
          self$`previousPage`
      }
      if (!is.null(self$`nextPage`)) {
        PaginateListDatafilesObject[['nextPage']] <-
          self$`nextPage`
      }
      if (!is.null(self$`lastPage`)) {
        PaginateListDatafilesObject[['lastPage']] <-
          self$`lastPage`
      }
      if (!is.null(self$`data`)) {
        PaginateListDatafilesObject[['data']] <-
          lapply(self$`data`, function(x) x$toJSON())
      }

      PaginateListDatafilesObject
    },
    fromJSON = function(PaginateListDatafilesJson) {
      PaginateListDatafilesObject <- jsonlite::fromJSON(PaginateListDatafilesJson)
      if (!is.null(PaginateListDatafilesObject$`pageSize`)) {
        self$`pageSize` <- PaginateListDatafilesObject$`pageSize`
      }
      if (!is.null(PaginateListDatafilesObject$`page`)) {
        self$`page` <- PaginateListDatafilesObject$`page`
      }
      if (!is.null(PaginateListDatafilesObject$`total`)) {
        self$`total` <- PaginateListDatafilesObject$`total`
      }
      if (!is.null(PaginateListDatafilesObject$`firstPage`)) {
        self$`firstPage` <- PaginateListDatafilesObject$`firstPage`
      }
      if (!is.null(PaginateListDatafilesObject$`previousPage`)) {
        self$`previousPage` <- PaginateListDatafilesObject$`previousPage`
      }
      if (!is.null(PaginateListDatafilesObject$`nextPage`)) {
        self$`nextPage` <- PaginateListDatafilesObject$`nextPage`
      }
      if (!is.null(PaginateListDatafilesObject$`lastPage`)) {
        self$`lastPage` <- PaginateListDatafilesObject$`lastPage`
      }
      if (!is.null(PaginateListDatafilesObject$`data`)) {
        self$`data` <- ApiClient$new()$deserializeObj(PaginateListDatafilesObject$`data`, "array[DatafileFull]", loadNamespace("didoscalie"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`pageSize`)) {
        sprintf(
        '"pageSize":
          "%s"
                ',
        self$`pageSize`
        )},
        if (!is.null(self$`page`)) {
        sprintf(
        '"page":
          %d
                ',
        self$`page`
        )},
        if (!is.null(self$`total`)) {
        sprintf(
        '"total":
          %d
                ',
        self$`total`
        )},
        if (!is.null(self$`firstPage`)) {
        sprintf(
        '"firstPage":
          "%s"
                ',
        self$`firstPage`
        )},
        if (!is.null(self$`previousPage`)) {
        sprintf(
        '"previousPage":
          "%s"
                ',
        self$`previousPage`
        )},
        if (!is.null(self$`nextPage`)) {
        sprintf(
        '"nextPage":
          "%s"
                ',
        self$`nextPage`
        )},
        if (!is.null(self$`lastPage`)) {
        sprintf(
        '"lastPage":
          "%s"
                ',
        self$`lastPage`
        )},
        if (!is.null(self$`data`)) {
        sprintf(
        '"data":
        [%s]
',
        paste(sapply(self$`data`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PaginateListDatafilesJson) {
      PaginateListDatafilesObject <- jsonlite::fromJSON(PaginateListDatafilesJson)
      self$`pageSize` <- PaginateListDatafilesObject$`pageSize`
      self$`page` <- PaginateListDatafilesObject$`page`
      self$`total` <- PaginateListDatafilesObject$`total`
      self$`firstPage` <- PaginateListDatafilesObject$`firstPage`
      self$`previousPage` <- PaginateListDatafilesObject$`previousPage`
      self$`nextPage` <- PaginateListDatafilesObject$`nextPage`
      self$`lastPage` <- PaginateListDatafilesObject$`lastPage`
      self$`data` <- ApiClient$new()$deserializeObj(PaginateListDatafilesObject$`data`, "array[DatafileFull]", loadNamespace("didoscalie"))
      self
    }
  )
)
