# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ServerError
#'
#' @description ServerError Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field code  integer 
#'
#' @field message  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ServerError <- R6::R6Class(
  'ServerError',
  public = list(
    `code` = NULL,
    `message` = NULL,
    initialize = function(
        `code`, `message`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`code`)) {
        stopifnot(is.numeric(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      ServerErrorObject <- list()
      if (!is.null(self$`code`)) {
        ServerErrorObject[['code']] <-
          self$`code`
      }
      if (!is.null(self$`message`)) {
        ServerErrorObject[['message']] <-
          self$`message`
      }

      ServerErrorObject
    },
    fromJSON = function(ServerErrorJson) {
      ServerErrorObject <- jsonlite::fromJSON(ServerErrorJson)
      if (!is.null(ServerErrorObject$`code`)) {
        self$`code` <- ServerErrorObject$`code`
      }
      if (!is.null(ServerErrorObject$`message`)) {
        self$`message` <- ServerErrorObject$`message`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`code`)) {
        sprintf(
        '"code":
          %d
                ',
        self$`code`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ServerErrorJson) {
      ServerErrorObject <- jsonlite::fromJSON(ServerErrorJson)
      self$`code` <- ServerErrorObject$`code`
      self$`message` <- ServerErrorObject$`message`
      self
    }
  )
)
