# DiDo - API diffusion
#
# API de diffusion des données de DiDo sur Internet
#
# The version of the OpenAPI document: 1.0.0
# Contact: support-dido@developpement-durable.gouv.fr
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ValidationError
#'
#' @description ValidationError Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field code  integer 
#'
#' @field message  character 
#'
#' @field errors  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ValidationError <- R6::R6Class(
  'ValidationError',
  public = list(
    `code` = NULL,
    `message` = NULL,
    `errors` = NULL,
    initialize = function(
        `code`, `message`, `errors`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`code`)) {
        stopifnot(is.numeric(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!is.null(`errors`)) {
        stopifnot(is.vector(`errors`), length(`errors`) != 0)
        sapply(`errors`, function(x) stopifnot(is.character(x)))
        self$`errors` <- `errors`
      }
    },
    toJSON = function() {
      ValidationErrorObject <- list()
      if (!is.null(self$`code`)) {
        ValidationErrorObject[['code']] <-
          self$`code`
      }
      if (!is.null(self$`message`)) {
        ValidationErrorObject[['message']] <-
          self$`message`
      }
      if (!is.null(self$`errors`)) {
        ValidationErrorObject[['errors']] <-
          self$`errors`
      }

      ValidationErrorObject
    },
    fromJSON = function(ValidationErrorJson) {
      ValidationErrorObject <- jsonlite::fromJSON(ValidationErrorJson)
      if (!is.null(ValidationErrorObject$`code`)) {
        self$`code` <- ValidationErrorObject$`code`
      }
      if (!is.null(ValidationErrorObject$`message`)) {
        self$`message` <- ValidationErrorObject$`message`
      }
      if (!is.null(ValidationErrorObject$`errors`)) {
        self$`errors` <- ApiClient$new()$deserializeObj(ValidationErrorObject$`errors`, "array[character]", loadNamespace("didoscalie"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`code`)) {
        sprintf(
        '"code":
          %d
                ',
        self$`code`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )},
        if (!is.null(self$`errors`)) {
        sprintf(
        '"errors":
           [%s]
        ',
        paste(unlist(lapply(self$`errors`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ValidationErrorJson) {
      ValidationErrorObject <- jsonlite::fromJSON(ValidationErrorJson)
      self$`code` <- ValidationErrorObject$`code`
      self$`message` <- ValidationErrorObject$`message`
      self$`errors` <- ApiClient$new()$deserializeObj(ValidationErrorObject$`errors`, "array[character]", loadNamespace("didoscalie"))
      self
    }
  )
)
